# Generated by Django 5.2.12 on 2026-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("DWELLING", "Dwelling/Construction"),
                            ("LAND", "Land/Infrastructure"),
                        ],
                        default="DWELLING",
                        max_length=10,
                    ),
                ),
                (
                    "contract_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent to Council"),
                            ("EXECUTED", "Executed"),
                            ("VARIED", "Varied"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("document", models.FileField(blank=True, upload_to="contracts/")),
                ("sent_to_council_date", models.DateField(blank=True, null=True)),
                ("council_executed_date", models.DateField(blank=True, null=True)),
                ("execution_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("KICKOFF", "Kick-off Meeting"),
                            ("INTERIM", "Interim Meeting"),
                            ("CLOSEOUT", "Close-out Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meeting_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("attendees", models.TextField(blank=True)),
                ("minutes", models.TextField(blank=True)),
                (
                    "action_items",
                    models.TextField(blank=True, help_text="Action items from meeting"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
