# Generated by Django 5.2.12 on 2026-04-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
        ("projects", "0003_project_project_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="land_project",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="project_type",
        ),
        migrations.AlterField(
            model_name="contract",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="projects.project",
            ),
        ),
    ]
