# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0002_initial"),
        ("councils", "0001_initial"),
        ("funding", "0002_initial"),
        ("land_infra", "0002_initial"),
        ("projects", "0001_initial"),
        ("works", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "option_number",
                    models.CharField(
                        blank=True, help_text="e.g., Option 1, Option 2", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Variation Types",
                "ordering": ["option_number", "name"],
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPTION_1", "Add Funding Schedule"),
                            ("OPTION_2", "Remove Funding Schedule"),
                            ("OPTION_3", "Change Contact Details"),
                            ("OPTION_4", "Replace Funding Schedule"),
                            ("OPTION_5", "Vary Funding Schedule Dates"),
                            ("OPTION_6", "Vary Scope of Works"),
                            ("OPTION_7", "Vary Land"),
                            ("OPTION_8", "Vary Funding"),
                            ("OPTION_9", "Vary Reporting Requirements"),
                            ("OPTION_OTHER", "Other"),
                        ],
                        help_text="The specific variation option type",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COUNCIL_SIGNED", "Council Signed"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("council_signed_date", models.DateField(blank=True, null=True)),
                ("department_executed_date", models.DateField(blank=True, null=True)),
                ("document_link", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "reporting_requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Required report items: monthly, quarterly, stage1, stage2",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="funding.fundingschedule",
                        verbose_name="Primary Funding Schedule",
                    ),
                ),
                (
                    "funding_schedules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Multiple FS can be affected by one variation",
                        related_name="variation_changes",
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "land_projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="variations",
                        to="land_infra.landproject",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="variations", to="projects.project"
                    ),
                ),
                (
                    "variation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="variations.variationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_source",
                    models.CharField(
                        choices=[
                            ("PROJECT", "Project"),
                            ("ADDRESS", "Address"),
                            ("WORK", "Work"),
                            ("FUNDING_SCHEDULE", "Funding Schedule"),
                            ("PAYMENT", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        help_text="ID of the source object (address, work, etc)"
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "is_captured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this change has been added to a variation",
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_changes",
                        to="variations.variation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariationContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attention", models.CharField(blank=True, max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "is_state_contact",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this is State contact. If False, Council contact.",
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this is new contact. If False, this is original.",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_details",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_type",
                    models.CharField(
                        choices=[
                            ("STAGE1_TARGET", "Stage 1 Target Date"),
                            ("STAGE2_TARGET", "Stage 2 Target Date"),
                            ("STAGE1_SUNSET", "Stage 1 Sunset Date"),
                            ("STAGE2_SUNSET", "Stage 2 Sunset Date"),
                            ("COMPLETION", "Completion Date"),
                            ("OTHER", "Other Date"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_date", models.DateField(blank=True, null=True)),
                ("new_date", models.DateField(blank=True, null=True)),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        help_text="Entity type (Project, FundingSchedule, Address, Work, Payment)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(
                        help_text="ID of the entity that was changed"
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "field_display",
                    models.CharField(
                        blank=True,
                        help_text="Display name for the field",
                        max_length=150,
                    ),
                ),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="variations.variation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Variation Execution Logs",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="VariationFundingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Which payment is being changed",
                        null=True,
                    ),
                ),
                (
                    "original_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "new_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_changes",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationFundingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("ORIGINAL", "Original"),
                            ("REPLACEMENT", "Replacement"),
                            ("ADDED", "Added"),
                            ("REMOVED", "Removed"),
                        ],
                        help_text="Relationship to this variation",
                        max_length=20,
                    ),
                ),
                (
                    "scope_of_works",
                    models.TextField(
                        blank=True,
                        help_text="Description of works for this funding schedule",
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_funding_schedules",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("OPTION_1", "Add Funding Schedule"),
                            ("OPTION_2", "Remove Funding Schedule"),
                            ("OPTION_3", "Change Contact Details"),
                            ("OPTION_4", "Replace Funding Schedule"),
                            ("OPTION_5", "Vary Dates"),
                            ("OPTION_6", "Vary Scope of Works"),
                            ("OPTION_7", "Vary Land"),
                            ("OPTION_8", "Vary Funding"),
                            ("OPTION_9", "Vary Reporting Requirements"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Which document option this implements",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Option-specific details stored as JSON",
                    ),
                ),
                (
                    "state_contact_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State contact: attention, phone, email, address",
                    ),
                ),
                ("council_contact_name", models.CharField(blank=True, max_length=255)),
                ("council_contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "council_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "update_council_contact",
                    models.BooleanField(
                        default=False, help_text="Also update council contact"
                    ),
                ),
                ("stage1_target_date", models.DateField(blank=True, null=True)),
                ("stage2_target_date", models.DateField(blank=True, null=True)),
                ("stage1_sunset_date", models.DateField(blank=True, null=True)),
                ("stage2_sunset_date", models.DateField(blank=True, null=True)),
                ("original_scope", models.TextField(blank=True)),
                ("new_scope", models.TextField(blank=True)),
                ("land_lot", models.CharField(blank=True, max_length=100)),
                ("land_plan", models.CharField(blank=True, max_length=100)),
                ("land_title_reference", models.CharField(blank=True, max_length=100)),
                ("land_street_address", models.TextField(blank=True)),
                ("land_annexure_ref", models.CharField(blank=True, max_length=255)),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "original_contingency",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "new_contingency",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("original_payment_split", models.CharField(blank=True, max_length=20)),
                ("new_payment_split", models.CharField(blank=True, max_length=20)),
                ("monthly_required", models.BooleanField(default=False)),
                ("quarterly_required", models.BooleanField(default=False)),
                ("stage1_required", models.BooleanField(default=False)),
                ("stage2_required", models.BooleanField(default=False)),
                ("reporting_notes", models.TextField(blank=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="addresses.address",
                    ),
                ),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="councils.council",
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "funding_schedules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="For multi-FS options",
                        related_name="+",
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="projects.project"
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="variations.variation",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="works.work",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VariationLandChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_lot", models.CharField(blank=True, max_length=100)),
                ("original_plan", models.CharField(blank=True, max_length=100)),
                (
                    "original_title_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("original_street_address", models.TextField(blank=True)),
                ("new_lot", models.CharField(blank=True, max_length=100)),
                ("new_plan", models.CharField(blank=True, max_length=100)),
                ("new_title_reference", models.CharField(blank=True, max_length=100)),
                ("new_street_address", models.TextField(blank=True)),
                (
                    "annexure_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to attached annexure",
                        max_length=255,
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_changes",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationReportingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY_TRACKER", "Monthly Tracker Report"),
                            ("QUARTERLY_REPORT", "Quarterly Report"),
                            ("STAGE1_REPORT", "Stage 1 Report"),
                            ("STAGE2_REPORT", "Stage 2 Report"),
                            ("OTHER", "Other Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "original_clause",
                    models.TextField(blank=True, help_text="Original clause text"),
                ),
                (
                    "new_clause",
                    models.TextField(blank=True, help_text="New clause text"),
                ),
                (
                    "attachment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to attachment describing the variation",
                        max_length=255,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_changes",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationScopeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_scope",
                    models.TextField(blank=True, help_text="Original scope of works"),
                ),
                (
                    "new_scope",
                    models.TextField(blank=True, help_text="New scope of works"),
                ),
                (
                    "annexure_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to attached annexure if applicable",
                        max_length=255,
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_changes",
                        to="variations.variation",
                    ),
                ),
            ],
        ),
    ]
