# Generated by Django 5.2.12 on 2026-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("DWELLING", "Dwelling/Construction"),
                            ("LAND", "Land/Infrastructure"),
                        ],
                        default="DWELLING",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("identified_date", models.DateField()),
                ("rectified_date", models.DateField(blank=True, null=True)),
                ("defects_liability_expiry", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
