# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("defects", "0001_initial"),
        ("land_infra", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="land_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defects",
                to="land_infra.landproject",
            ),
        ),
        migrations.AddField(
            model_name="defect",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defects",
                to="projects.project",
            ),
        ),
    ]
