# Generated by Django 5.2.12 on 2026-04-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defect",
            name="land_project",
        ),
        migrations.RemoveField(
            model_name="defect",
            name="project_type",
        ),
    ]
