# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funding", "0002_initial"),
        ("land_infra", "0002_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("DWELLING", "Dwelling/Construction"),
                            ("LAND", "Land/Infrastructure"),
                        ],
                        default="DWELLING",
                        max_length=10,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage of Funding"),
                            ("FIXED", "Fixed Amount"),
                            ("REIMBURSEMENT", "Reimbursement (Actual Expenses)"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="e.g., 30 for 30%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Payment"),
                            ("SECOND", "Second Payment"),
                            ("THIRD", "Third Payment"),
                            ("INTERIM", "Interim Payment"),
                            ("FINAL", "Final Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_split",
                    models.CharField(
                        choices=[
                            ("30/60/10", "Standard (30/60/10)"),
                            ("90/10", "Alternative (90/10)"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="30/60/10",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "gl_code",
                    models.CharField(
                        blank=True, help_text="GL code from program", max_length=50
                    ),
                ),
                (
                    "business_case_ref",
                    models.CharField(
                        blank=True,
                        help_text="Business case reference from program",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECOMMENDED", "Recommended"),
                            ("APPROVED", "Approved"),
                            ("RELEASED", "Released"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tax_invoice_reference",
                    models.CharField(
                        blank=True,
                        help_text="Tax Invoice or RCTI reference number",
                        max_length=100,
                    ),
                ),
                (
                    "sap_payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="SAP Payment Document Number",
                        max_length=100,
                    ),
                ),
                (
                    "sap_cost_centre",
                    models.CharField(
                        blank=True, help_text="SAP Cost Centre", max_length=50
                    ),
                ),
                (
                    "document_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPENDOCS", "OpenDocs Content Manager"),
                            ("SHARED_DRIVE", "Shared Network Drive"),
                            ("LOCAL", "Local Upload"),
                        ],
                        help_text="Where documents are stored",
                        max_length=20,
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to OpenDocs or SharePoint document",
                        max_length=500,
                    ),
                ),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to document on shared drive (e.g., \\\\server\\folder\\file.pdf)",
                        max_length=500,
                    ),
                ),
                (
                    "document_added_date",
                    models.DateField(
                        blank=True,
                        help_text="Date document was added/referenced",
                        null=True,
                    ),
                ),
                ("recommended_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Date payment was released to Finance",
                        null=True,
                    ),
                ),
                (
                    "release_sap_reference",
                    models.CharField(
                        blank=True,
                        help_text="SAP Payment Document Number (from release)",
                        max_length=100,
                    ),
                ),
                (
                    "release_receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt/Transaction Reference Number",
                        max_length=100,
                    ),
                ),
                (
                    "release_document_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPENDOCS", "OpenDocs Content Manager"),
                            ("SHARED_DRIVE", "Shared Network Drive"),
                            ("LOCAL", "Local Upload"),
                        ],
                        help_text="Where release receipt is stored",
                        max_length=20,
                    ),
                ),
                (
                    "release_document_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to receipt in OpenDocs/SharePoint",
                        max_length=500,
                    ),
                ),
                (
                    "release_document_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to receipt on shared drive",
                        max_length=500,
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from release (e.g., finance team comments)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funding_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="funding.fundingschedule",
                    ),
                ),
                (
                    "land_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="land_infra.landproject",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="projects.project",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
