- name: bug
  color: d73a49
  description: Something isn't working
- name: triage
  color: ffffff
  description: Needs triage
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: refactor
  color: fbca04
  description: Code refactoring
- name: maintenance
  color: fbca04
  description: Maintenance tasks
- name: database
  color: 0e8a16
  description: Database related
- name: schema
  color: 0e8a16
  description: Schema changes
- name: infrastructure
  color: 1d76db
  description: Infrastructure and configuration