# Generated by Django 5.2.12 on 2026-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("lot", models.CharField(blank=True, max_length=100)),
                ("plan", models.CharField(blank=True, max_length=100)),
                (
                    "residence_plc_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reside PLC system reference",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Suburb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=4)),
                ("state", models.CharField(default="QLD", max_length=3)),
                ("state_electorate", models.CharField(blank=True, max_length=100)),
                ("federal_electorate", models.CharField(blank=True, max_length=100)),
                ("qhigi_region", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
