# Generated by Django 5.2.12 on 2026-05-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_notice_noticetarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkStepDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Step Definition",
                "verbose_name_plural": "Work Step Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkStepGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Standard 3BR New House, Minor Extension",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Step Group",
                "verbose_name_plural": "Work Step Groups",
                "ordering": ["work_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkStepGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "cost_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("expected_duration_days", models.PositiveIntegerField(default=0)),
                (
                    "stage_gate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No gate"),
                            ("STAGE1", "Stage 1 completion"),
                            ("STAGE2", "Stage 2 completion"),
                        ],
                        default="",
                        help_text="Mark this step as the completion point for Stage 1 or Stage 2 works",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Step Group Item",
                "verbose_name_plural": "Work Step Group Items",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="workstep",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveConstraint(
            model_name="noticetarget",
            name="unique_notice_target",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="core_commen_content_3b9055_idx",
            old_name="core_commen_content_idx",
        ),
        migrations.RenameIndex(
            model_name="noticetarget",
            new_name="core_notice_content_7102ac_idx",
            old_name="core_notice_ct_obj_idx",
        ),
        migrations.AddField(
            model_name="payment",
            name="forecast_release_date",
            field=models.DateField(
                blank=True,
                help_text="Forecast release date for Capital Grants cashflow planning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="cashflow_method",
            field=models.CharField(
                choices=[
                    ("MILESTONE", "Capital Grants (Payment Milestone)"),
                    ("WORKSTEP", "Capital Works (WorkStep Progressive)"),
                ],
                default="MILESTONE",
                help_text="How cashflow is forecast for this work item",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workstep",
            name="actual_completion_date",
            field=models.DateField(
                blank=True,
                help_text="Actual completion date — triggers cascade recalculation of subsequent forecasts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workstep",
            name="forecast_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workstep",
            name="forecast_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workstep",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Deactivate to mark step as n/a for this work item",
            ),
        ),
        migrations.AddField(
            model_name="workstep",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Step sequence for cumulative calculation"
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="short_code",
            field=models.CharField(
                blank=True,
                help_text="Abbreviation for reports, e.g. DH, TRI, EXT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workstep",
            name="expected_cost_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="workstep",
            name="expected_duration_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workstep",
            name="step_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="noticetarget",
            unique_together={("notice", "content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="workstep",
            unique_together={("work", "order")},
        ),
        migrations.AddField(
            model_name="workstepgroup",
            name="work_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="step_groups",
                to="core.worktype",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="step_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when cashflow_method = WORKSTEP",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="core.workstepgroup",
            ),
        ),
        migrations.AddField(
            model_name="workstepgroupitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.workstepgroup",
            ),
        ),
        migrations.AddField(
            model_name="workstepgroupitem",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_items",
                to="core.workstepdefinition",
            ),
        ),
        migrations.AddField(
            model_name="workstep",
            name="group_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Source group item this step was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="core.workstepgroupitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workstepgroupitem",
            unique_together={("group", "order")},
        ),
    ]
