# Generated by Django 5.2.12 on 2026-05-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_workstepdefinition_workstepgroup_workstepgroupitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="actual_start_date",
            field=models.DateField(
                blank=True,
                help_text="Date construction actually started — anchors the rolling step forecast",
                null=True,
            ),
        ),
    ]
