# Generated by Django 5.2.12 on 2026-05-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_work_actual_start_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.SlugField(
                        help_text="Short code e.g. on_site, flatpack", unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Construction Method",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="council",
            name="default_principal_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Default Principal Officer applied to new projects for this council",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_principal_councils",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="council",
            name="default_senior_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Default Senior Officer applied to new projects for this council",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_senior_councils",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="principal_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="RICD Principal Officer responsible for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="principal_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="senior_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="RICD Senior Officer with carriage of this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senior_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ForwardRPFAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference / agreement number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("EXECUTED", "Executed"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("date_sent_to_council", models.DateField(blank=True, null=True)),
                ("date_council_signed", models.DateField(blank=True, null=True)),
                ("date_delegate_signed", models.DateField(blank=True, null=True)),
                (
                    "document_uri",
                    models.URLField(
                        blank=True,
                        help_text="Link to executed agreement in OpenDocs/Google Drive",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.OneToOneField(
                        help_text="Council this agreement is with (one agreement per council)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.council",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projects funded under this Forward RPF agreement",
                        related_name="forward_rpf_agreements",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forward RPF Agreement",
                "verbose_name_plural": "Forward RPF Agreements",
                "ordering": ["council__name"],
            },
        ),
        migrations.CreateModel(
            name="InterimFRPAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference / agreement number",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("EXECUTED", "Executed"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("date_sent_to_council", models.DateField(blank=True, null=True)),
                ("date_council_signed", models.DateField(blank=True, null=True)),
                ("date_delegate_signed", models.DateField(blank=True, null=True)),
                (
                    "document_uri",
                    models.URLField(
                        blank=True,
                        help_text="Link to executed agreement in OpenDocs/Google Drive",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.OneToOneField(
                        help_text="Council this agreement is with (one agreement per council)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.council",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projects funded under this Interim FRP agreement",
                        related_name="interim_frp_agreements",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interim FRP Agreement",
                "verbose_name_plural": "Interim FRP Agreements",
                "ordering": ["council__name"],
            },
        ),
    ]
