# Generated by Django 5.2.12 on 2026-05-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_constructionmethod_council_default_principal_officer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worksteptemplate",
            name="work_type",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="document",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="actual_total",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="contingency",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="notional_total",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="payment_split",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="total_funding",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="works",
        ),
        migrations.RemoveField(
            model_name="quarterlyreportattachment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="stagereportattachment",
            name="file",
        ),
        migrations.AddField(
            model_name="contract",
            name="document_uri",
            field=models.URLField(
                blank=True,
                help_text="Link to contract document in OpenDocs/Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="funding_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Funding schedule linked to this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.fundingschedule",
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreportattachment",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Link to attachment in OpenDocs/Google Drive"
            ),
        ),
        migrations.AddField(
            model_name="stagereportattachment",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Link to attachment in OpenDocs/Google Drive"
            ),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="contact_details",
            field=models.JSONField(
                blank=True, default=dict, help_text="attention, phone, email, address"
            ),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="councils",
            field=models.ManyToManyField(
                blank=True, related_name="funding_schedules", to="core.council"
            ),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="land_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="scope_of_works",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="stage1_sunset_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="stage1_target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="stage2_sunset_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="stage2_target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("identified_date", models.DateField()),
                ("rectified_date", models.DateField(blank=True, null=True)),
                ("defects_liability_expiry", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FundingApproval",
        ),
        migrations.DeleteModel(
            name="WorkStepTemplate",
        ),
    ]
