# Generated by Django 5.2.12 on 2026-05-22 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_stage_items_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageitemdefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stageitemgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stageitemgroupitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stagereport",
            name="funding_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Funding Schedule this report is linked to (use this XOR interim_frp XOR forward_rpf)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stage_reports",
                to="core.fundingschedule",
            ),
        ),
        migrations.AlterField(
            model_name="stagereportattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stagereportitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
