# Generated by Django 5.2.12 on 2026-05-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_stage_report_alter_drift"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaim",
            name="sap_document_reference",
            field=models.CharField(
                blank=True,
                help_text="SAP Recipient Created Tax Invoice (RCTI) or SAP payment document number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.AlterField(
            model_name="forwardrpfagreement",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.AlterField(
            model_name="fundingagreement",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.AlterField(
            model_name="interimfrpagreement",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.AlterField(
            model_name="paymentrule",
            name="config_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Auto-synced from milestone rows; do not edit directly.",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrule",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Increment for new versions"
            ),
        ),
        migrations.AlterField(
            model_name="quarterlyreportattachment",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.AlterField(
            model_name="stagereportattachment",
            name="document_uri",
            field=models.URLField(
                blank=True, help_text="Windows Share Drive, Sharepoint or OpenDocs link"
            ),
        ),
        migrations.CreateModel(
            name="ExpenseClaimAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_uri",
                    models.URLField(
                        blank=True,
                        help_text="Windows Share Drive, Sharepoint or OpenDocs link",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Invoice 1234', 'SAP RCTI'",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.expenseclaim",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_claim_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRuleMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'First', 'Stage 1 completion'", max_length=100
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="0.00 - 100.00", max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="core.paymentrule",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("rule", "order")},
            },
        ),
    ]
