# Generated by Django 5.2.12 on 2026-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_pr1_payment_rule_expense_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="max_bedrooms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Typical highest bedroom count (e.g. 5). Costs outside the range are still allowed but flagged.",
            ),
        ),
        migrations.AddField(
            model_name="worktype",
            name="min_bedrooms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Typical lowest bedroom count (e.g. 3). Bulk-update notional costs uses this range.",
            ),
        ),
    ]
