# Generated by Django 5.2.12 on 2026-05-23 23:01

import django.db.models.deletion
from django.db import migrations, models




def _backfill_electorates(apps, schema_editor):
    """For each existing Suburb/Council, get_or_create lookup rows from the
    free-text electorate / region columns and set the corresponding FK."""
    Suburb = apps.get_model("core", "Suburb")
    Council = apps.get_model("core", "Council")
    StateElectorate = apps.get_model("core", "StateElectorate")
    FederalElectorate = apps.get_model("core", "FederalElectorate")
    QhigiRegion = apps.get_model("core", "QhigiRegion")

    def _lookup(model, name):
        name = (name or "").strip()
        if not name:
            return None
        obj, _ = model.objects.get_or_create(name=name)
        return obj

    for s in Suburb.objects.all():
        s.state_electorate_link = _lookup(StateElectorate, s.state_electorate)
        s.federal_electorate_link = _lookup(FederalElectorate, s.federal_electorate)
        s.qhigi_region_link = _lookup(QhigiRegion, s.qhigi_region)
        s.save()

    for c in Council.objects.all():
        c.state_electorate_link = _lookup(StateElectorate, c.state_electorate)
        c.federal_electorate_link = _lookup(FederalElectorate, c.federal_electorate)
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_stage_report_per_fs"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederalElectorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Federal Electorate",
                "verbose_name_plural": "Federal Electorates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QhigiRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QHIGI Region",
                "verbose_name_plural": "QHIGI Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StateElectorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "State Electorate",
                "verbose_name_plural": "State Electorates",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="council",
            name="federal_electorate",
            field=models.CharField(
                blank=True,
                help_text="Federal Electorate (legacy free text)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="council",
            name="state_electorate",
            field=models.CharField(
                blank=True,
                help_text="State Electorate (legacy free text)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fundingagreement",
            name="council",
            field=models.OneToOneField(
                help_text="The single Remote Capital Program Funding Agreement for this council",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_agreement",
                to="core.council",
            ),
        ),
        migrations.AddField(
            model_name="council",
            name="federal_electorate_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Federal Electorate (linked)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="councils",
                to="core.federalelectorate",
            ),
        ),
        migrations.AddField(
            model_name="suburb",
            name="federal_electorate_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suburbs",
                to="core.federalelectorate",
            ),
        ),
        migrations.AddField(
            model_name="suburb",
            name="qhigi_region_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suburbs",
                to="core.qhigiregion",
            ),
        ),
        migrations.AddField(
            model_name="council",
            name="state_electorate_link",
            field=models.ForeignKey(
                blank=True,
                help_text="State Electorate (linked)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="councils",
                to="core.stateelectorate",
            ),
        ),
        migrations.AddField(
            model_name="suburb",
            name="state_electorate_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suburbs",
                to="core.stateelectorate",
            ),
        ),
        # Data backfill: dedupe existing free-text values into lookup rows + set FK
        migrations.RunPython(
            _backfill_electorates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
