# Generated by Django 5.2.12 on 2026-05-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_simplify_officer_roles"),
        ("core", "0017_pr4_fa_1to1_electorate_fks"),
    ]

    operations = []
