# Generated by Django 5.2.12 on 2026-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_merge_20260524_2251"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingschedule",
            name="actual_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="contingency",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="notional_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="payment_split",
            field=models.CharField(
                choices=[
                    ("30/60/10", "Standard (30/60/10)"),
                    ("90/10", "Alternative (90/10)"),
                    ("CUSTOM", "Custom"),
                ],
                default="30/60/10",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="total_funding",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="works",
            field=models.ManyToManyField(
                blank=True,
                help_text="Works funded by this schedule",
                related_name="funding_schedules",
                to="core.work",
            ),
        ),
    ]
