# Generated by Django 5.2.12 on 2026-05-25; hand-edited to preserve data.
#
# Order:
#   1. Add new fields/tables (BFAItem, council FKs on BFA + FS)
#   2. RunPython data backfill: copy BFA.project/funding_amount/contingency_amount
#      into a BFAItem row; populate BFA.council from project.council; populate
#      FS.council from funding_agreement.council (or project.council fallback)
#   3. Drop the old BFA fields + FS.contingency
#   4. Add the unique-per-council constraint on FS.schedule_number

import django.db.models.deletion
from django.db import migrations, models


def backfill_bfa_items_and_councils(apps, schema_editor):
    BriefFinancialApproval = apps.get_model('core', 'BriefFinancialApproval')
    BFAItem = apps.get_model('core', 'BriefFinancialApprovalItem')
    FundingSchedule = apps.get_model('core', 'FundingSchedule')

    # 1) Move each BFA's single project + funding to a new BFAItem row
    for bfa in BriefFinancialApproval.objects.all():
        project_id = getattr(bfa, 'project_id', None)
        if project_id:
            BFAItem.objects.update_or_create(
                bfa=bfa, project_id=project_id,
                defaults={
                    'funding_amount': bfa.funding_amount or 0,
                    'contingency_amount': bfa.contingency_amount or 0,
                    'cost_centre': '',
                    'gl_code': '',
                },
            )
            if not bfa.council_id:
                try:
                    bfa.council_id = bfa.project.council_id
                    bfa.save(update_fields=['council'])
                except Exception:
                    pass

    # 2) Backfill FS.council from funding_agreement.council, or project.council
    for fs in FundingSchedule.objects.all():
        if fs.council_id:
            continue
        council_id = None
        if fs.funding_agreement_id:
            council_id = getattr(fs.funding_agreement, 'council_id', None)
        if not council_id and fs.project_id:
            try:
                council_id = fs.project.council_id
            except Exception:
                council_id = None
        if council_id:
            fs.council_id = council_id
            fs.save(update_fields=['council'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_fundingschedule_master_fields"),
    ]

    operations = [
        # --- Step 1: create new table + columns ---
        migrations.CreateModel(
            name="BriefFinancialApprovalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_centre", models.CharField(blank=True, max_length=50)),
                ("gl_code", models.CharField(blank=True, max_length=50)),
                (
                    "funding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["project__name"],
            },
        ),
        migrations.AddField(
            model_name="brieffinancialapprovalitem",
            name="bfa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.brieffinancialapproval",
            ),
        ),
        migrations.AddField(
            model_name="brieffinancialapprovalitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bfa_items",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="brieffinancialapproval",
            name="council",
            field=models.ForeignKey(
                blank=True,
                help_text="Council this approval belongs to (derived from items)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_approvals",
                to="core.council",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="council",
            field=models.ForeignKey(
                blank=True,
                help_text="Council that owns this schedule (derived from funding_agreement.council)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funding_schedules_via_council",
                to="core.council",
            ),
        ),
        migrations.AlterField(
            model_name="brieffinancialapproval",
            name="mincor_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="MINCOR / approval reference (groups projects under one approval)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="brieffinancialapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),

        # --- Step 2: data backfill (must run BEFORE the field drops below) ---
        migrations.RunPython(backfill_bfa_items_and_councils, reverse_backfill),

        # --- Step 3: drop the now-superseded fields ---
        migrations.RemoveField(
            model_name="brieffinancialapproval",
            name="contingency_amount",
        ),
        migrations.RemoveField(
            model_name="brieffinancialapproval",
            name="funding_amount",
        ),
        migrations.RemoveField(
            model_name="brieffinancialapproval",
            name="project",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="contingency",
        ),

        # --- Step 4: per-council uniqueness on FS.schedule_number ---
        migrations.AddConstraint(
            model_name="fundingschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("council__isnull", False)),
                fields=("council", "schedule_number"),
                name="fundingschedule_unique_number_per_council",
            ),
        ),
        migrations.AddConstraint(
            model_name="brieffinancialapprovalitem",
            constraint=models.UniqueConstraint(
                fields=("bfa", "project"), name="bfa_item_unique_project"
            ),
        ),
    ]
