# Generated by Django 5.2.12 on 2026-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_fs_council_bfa_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brieffinancialapproval",
            name="council",
        ),
        migrations.AddField(
            model_name="brieffinancialapproval",
            name="document_uri",
            field=models.URLField(
                blank=True,
                help_text="Link to the brief document (OpenDocs / SharePoint / Shared Drive folder or file).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_centre",
            field=models.CharField(
                blank=True,
                help_text="Per-project cost centre code (e.g. 316333). Inherited into BFA item rows.",
                max_length=50,
            ),
        ),
    ]
