# Generated by Django 5.2.12 on 2026-05-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_bfa_drop_council_add_docuri_project_cost_centre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="cost_centre",
        ),
        migrations.AddField(
            model_name="program",
            name="cost_centre",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cost centre code for this program (inherited by BFA items + reports).",
                max_length=50,
            ),
        ),
    ]
