# Generated by Django 5.2.12 on 2026-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_seed_qld_suburbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="forecast_handover_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Rolling estimate of when the asset will be handed to the council/department.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="forecast_practical_completion_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Rolling estimate of Practical Completion. Driven by Monthly Tracker progress; can be manually overridden.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="handover_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Actual Handover date — when the asset has been delivered.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="practical_completion_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Actual Practical Completion date. Set when the Stage 2 PC item is approved (or entered manually).",
                null=True,
            ),
        ),
    ]
