# Generated by Django 5.2.12 on 2026-05-25 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_work_pc_handover_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brieffinancialapproval",
            name="human_rights_assessment_uri",
            field=models.URLField(
                blank=True,
                help_text="Link to the Human Rights Assessment that accompanies this brief (required alongside the FAS for financial approval).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="council",
            name="lead_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="Default FNC officer assigned to this council. Individual projects may override via Project.lead_officer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_councils",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="council_contribution_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Council's own contribution toward the works (Item 6 of FS). Usually $0 — fill in only when Council co-funds.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="lease_clause_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RHP", "Council is a Registered Housing Provider"),
                    ("40Y", "40-year lease to the State"),
                    ("NA", "Not applicable"),
                ],
                help_text="Item 7 of Funding Schedule QA: which lease clause applies to this schedule. Drives the wording inserted in the FS template.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead_officer",
            field=models.ForeignKey(
                blank=True,
                help_text="FNC officer for this project. Overrides Council.lead_officer (use effective_lead_officer for resolved value).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
