# Generated by Django 5.2.12 on 2026-05-25 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_mvp_phase_a_foundation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarterlyreport",
            name="adverse_matters",
            field=models.TextField(
                blank=True,
                help_text="Any adverse matters connected with the Funding or the Works.",
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="bank_statement_uri",
            field=models.URLField(
                blank=True,
                help_text="Link to the council's bank statement(s) for this quarter.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="council_contribution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reported Council contribution toward the Works this quarter.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="indigenous_businesses_engaged",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of Indigenous local businesses engaged.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="local_indigenous_employed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of local Aboriginal or Torres Strait Islander people employed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="other_party_contribution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reported third-party contributions (e.g. Commonwealth).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="pct_works_completed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of works completed to date (0–100).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="total_employed",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total number of people employed on the projects.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="total_expenditure_to_date",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Council's reported total expenditure on the Works to date.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyreport",
            name="unspent_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount of unspent Funding still held by Council.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="QuarterlyReportExpenditureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="What was paid for (e.g. 'Plumbing rough-in, Lot 12').",
                        max_length=255,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Who was paid (contractor / supplier).",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "spend_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the expense was incurred.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenditure_items",
                        to="core.quarterlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["spend_date", "id"],
            },
        ),
    ]
