# Generated by Django 5.2.12 on 2026-05-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_seed_workstep_and_stage_catalogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="bathrooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="car_accommodation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="floor_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="floor_number",
            field=models.CharField(
                blank=True,
                help_text="Floor number for apartments (e.g. '3', 'G')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="frame_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="kitchens_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="land_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AVAIL", "Available"),
                    ("ACQ", "Acquired"),
                    ("CROWN", "Crown Land"),
                    ("TPEND", "Transfer Pending"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="lease_executed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="lease_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NR", "Not Required"),
                    ("PEND", "Pending"),
                    ("EXEC", "Executed"),
                ],
                default="",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="livable_housing_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                ],
                default="",
                help_text="Livable Housing Design guideline level (Silver / Gold / Platinum)",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="living_rooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="roof_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PH", "Public Housing"),
                    ("AH", "Affordable Housing"),
                    ("CH", "Community Housing"),
                    ("MX", "Mixed Use"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="wall_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="cli_no",
            field=models.CharField(
                blank=True,
                help_text="Client reference number (hidden in UI by default — toggle via Advanced section)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="financial_year_completed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2025-2026", "2025-2026 (Current)"),
                    ("2026-2027", "2026-2027"),
                    ("2027-2028", "2027-2028"),
                    ("2028-2029", "2028-2029"),
                    ("2029-2030", "2029-2030"),
                    ("2030-2031", "2030-2031"),
                    ("2031-2032", "2031-2032"),
                    ("2032-2033", "2032-2033"),
                    ("2033-2034", "2033-2034"),
                    ("2034-2035", "2034-2035"),
                    ("2035-2036", "2035-2036"),
                    ("2036-2037", "2036-2037"),
                    ("2037-2038", "2037-2038"),
                    ("2038-2039", "2038-2039"),
                    ("2039-2040", "2039-2040"),
                ],
                default="",
                help_text="Financial year in which the project was completed",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="initial_caa_date",
            field=models.DateField(
                blank=True,
                help_text="Initial date of CAA (hidden in UI by default — toggle via Advanced section)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sap_ion",
            field=models.CharField(
                blank=True, help_text="SAP Internal Order Number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="core.contractor",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="costs_finalised",
            field=models.BooleanField(
                default=False,
                help_text="All costs for this work item have been finalised",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="drawing_no",
            field=models.CharField(
                blank=True, help_text="Construction drawing reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="floor_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Floor area in m²",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="forecast_final_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Latest forecast of the final cost for this work item",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LandPreCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NT", "Native Title"),
                            ("ENV", "Environmental Assessment"),
                            ("DA", "Development Application"),
                            ("SUR", "Survey"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RED", "Not started"),
                            ("AMB", "Outstanding issues"),
                            ("GRN", "Addressed / No issues"),
                        ],
                        default="RED",
                        max_length=3,
                    ),
                ),
                (
                    "native_title_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ILUA", "ILUA"),
                            ("24JAA", "Statutory 24JAA"),
                            ("24KAA", "Statutory 24KAA"),
                            ("EXT", "Extinguished (Not Applicable)"),
                        ],
                        default="",
                        help_text="Only applicable when category = Native Title",
                        max_length=5,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_pre_conditions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land Pre-Condition",
                "verbose_name_plural": "Land Pre-Conditions",
                "ordering": ["category"],
                "unique_together": {("project", "category")},
            },
        ),
    ]
