# Generated by Django 5.2.12 on 2026-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_quarterlyreport_declaration_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reports_email",
                    models.EmailField(
                        default="reports@ricd.qld.gov.au",
                        help_text="Email address that quarterly-report submission emails are addressed to.",
                        max_length=254,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
