# Generated by Django 5.2.12 on 2026-05-31 13:07

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="project_documents/",
                validators=[apps.core.validators.validate_upload],
            ),
        ),
    ]
