# Generated by Django 5.2.12 on 2026-06-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_projectdocument_file_validator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingschedule",
            name="payment_split",
        ),
    ]
