# Generated by Django 5.2.12 on 2026-06-01 05:00

from django.db import migrations, models


_MOVED_FIELDS = [
    "floor_number", "livable_housing_level", "usage_type",
    "floor_material", "frame_material", "wall_material", "roof_material",
    "car_accommodation", "bathrooms_count", "kitchens_count", "living_rooms_count",
]


def copy_address_to_works(apps, schema_editor):
    """Copy the dwelling/as-built fields from each Address onto its child Works.

    Address->Work is one-to-many, so every Work at an address inherits that
    address's prior values. Runs after the Work columns are added and before
    the Address columns are dropped.
    """
    Work = apps.get_model("core", "Work")
    for work in Work.objects.exclude(address__isnull=True).select_related("address"):
        addr = work.address
        changed = False
        for f in _MOVED_FIELDS:
            val = getattr(addr, f)
            if val not in (None, ""):
                setattr(work, f, val)
                changed = True
        if changed:
            work.save(update_fields=_MOVED_FIELDS)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_fundingschedule_payment_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="bathrooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="car_accommodation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="work",
            name="floor_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="work",
            name="floor_number",
            field=models.CharField(
                blank=True,
                help_text="Floor number for apartments (e.g. '3', 'G')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frame_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="work",
            name="kitchens_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="livable_housing_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                ],
                default="",
                help_text="Livable Housing Design guideline level (Silver / Gold / Platinum)",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="living_rooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="roof_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="work",
            name="usage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PH", "Public Housing"),
                    ("AH", "Affordable Housing"),
                    ("CH", "Community Housing"),
                    ("MX", "Mixed Use"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="wall_material",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(copy_address_to_works, noop_reverse),
        migrations.RemoveField(
            model_name="address",
            name="bathrooms_count",
        ),
        migrations.RemoveField(
            model_name="address",
            name="car_accommodation",
        ),
        migrations.RemoveField(
            model_name="address",
            name="floor_material",
        ),
        migrations.RemoveField(
            model_name="address",
            name="floor_number",
        ),
        migrations.RemoveField(
            model_name="address",
            name="frame_material",
        ),
        migrations.RemoveField(
            model_name="address",
            name="kitchens_count",
        ),
        migrations.RemoveField(
            model_name="address",
            name="livable_housing_level",
        ),
        migrations.RemoveField(
            model_name="address",
            name="living_rooms_count",
        ),
        migrations.RemoveField(
            model_name="address",
            name="roof_material",
        ),
        migrations.RemoveField(
            model_name="address",
            name="usage_type",
        ),
        migrations.RemoveField(
            model_name="address",
            name="wall_material",
        ),
    ]
