# Generated by Django 5.2.12 on 2026-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_payment_forecast_anchor_payment_forecast_offset_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="forecast_anchor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual (I set the forecast date)"),
                    ("PROJECT_PC", "Project forecast practical completion"),
                ],
                default="MANUAL",
                help_text="What drives the forecast release date. PROJECT_PC tracks the project's forecast practical completion automatically.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="forecast_offset_days",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Days after the anchor milestone (e.g. 14 = pay 14 days after PC).",
            ),
        ),
    ]
