# Generated by Django 5.2.12 on 2026-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_payment_forecast_anchor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="forecast_anchor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual (I set the forecast date)"),
                    ("PROJECT_START", "Project start date"),
                    ("SITE_ESTAB", "Site establishment (Monthly Tracker)"),
                    ("PROJECT_PC", "Project forecast practical completion"),
                ],
                default="MANUAL",
                help_text="What drives the forecast release date. PROJECT_PC tracks the project's forecast practical completion automatically.",
                max_length=20,
            ),
        ),
    ]
