# Generated by Django 5.2.12 on 2026-06-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_payment_forecast_anchor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="forecast_offset_days",
        ),
        migrations.AlterField(
            model_name="payment",
            name="forecast_anchor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual (I set the forecast date)"),
                    ("SCHEDULED", "Scheduled (follows the work group milestone)"),
                ],
                default="MANUAL",
                help_text="MANUAL = you set the forecast date. SCHEDULED = it follows the work group's payment milestone schedule automatically.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentMilestoneSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Standard 30/60/10'", max_length=200
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Fallback schedule used when a project's work group has no schedule.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_step_group",
                    models.OneToOneField(
                        blank=True,
                        help_text="The work step group this payment timing applies to. Leave blank for the global default schedule.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedule",
                        to="core.workstepgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Milestone Schedule",
                "verbose_name_plural": "Payment Milestone Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestoneRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Payment"),
                            ("SECOND", "Second Payment"),
                            ("THIRD", "Third Payment"),
                            ("INTERIM", "Interim Payment"),
                            ("FINAL", "Final Payment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("PROJECT_START", "Project start date"),
                            ("WORK_STEP", "Work step completion (named)"),
                            ("PROJECT_PC", "Project forecast practical completion"),
                            ("MANUAL", "Manual (no auto date)"),
                        ],
                        default="WORK_STEP",
                        max_length=20,
                    ),
                ),
                (
                    "offset_days",
                    models.IntegerField(
                        default=14,
                        help_text="Days after the milestone (e.g. 14 = pay 14 days after).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_step_definition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which step to track when anchor is 'Work step completion'.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_rules",
                        to="core.workstepdefinition",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="core.paymentmilestoneschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Milestone Rule",
                "verbose_name_plural": "Payment Milestone Rules",
                "ordering": ["payment_type"],
                "unique_together": {("schedule", "payment_type")},
            },
        ),
    ]
