# Generated by Django 5.2.12 on 2026-06-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_seed_standard_payment_milestone_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reconciled_date",
            field=models.DateField(
                blank=True,
                help_text="Date this payment was reconciled/acquitted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="work",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific work (dwelling/lot) this payment funds, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.work",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RECOMMENDED", "Recommended"),
                    ("APPROVED", "Approved"),
                    ("RELEASED", "Released"),
                    ("RECONCILED", "Reconciled (acquitted)"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
