# Generated by Django 5.2.12 on 2026-06-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_payment_reconciled_date_payment_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
