# Generated by Django 5.2.12 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_project_archived_at_project_archived_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="trade_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARPENTER", "Carpenter"),
                    ("BUILDER", "Builder"),
                    ("ELECTRICIAN", "Electrician"),
                    ("PLUMBER", "Plumber"),
                    ("CONCRETER", "Concreter"),
                    ("LANDSCAPER", "Landscaper"),
                    ("CIVIL_ENGINEER", "Civil Engineer"),
                    ("EARTHWORKS", "Earthworks"),
                    ("PAINTER", "Painter"),
                    ("ROOFER", "Roofing"),
                    ("TILER", "Tiler"),
                    ("BRICKLAYER", "Bricklayer"),
                    ("PLANNER", "Town Planner/Urban Planner"),
                    ("ARCHITECT", "Architect"),
                    ("SURVEYOR", "Surveyor"),
                    ("ENGINEER", "Engineer"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
    ]
