# Generated by Django 5.2.12 on 2026-06-08 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_contractor_trade_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="qbuild_delivered",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="QBUILD (State builder) delivers this project — no Council funding schedule or Council reporting; FNC pays QBUILD directly.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="funding_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.fundingschedule",
            ),
        ),
    ]
