# Generated by Django 5.2.12 on 2026-06-09 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_project_qbuild_delivered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("PAYMENT_RELEASED", "Payment released"),
                            ("AGREEMENT_SIGNED", "Funding agreement signed"),
                            ("REPORT_APPROVED", "Report approved"),
                            ("REPORT_REJECTED", "Report rejected / returned"),
                            ("PROJECT_COMPLETED", "Project completed"),
                            ("MONTHLY_TRACKER_OVERDUE", "Monthly tracker overdue"),
                            ("QUARTERLY_REPORT_OVERDUE", "Quarterly report overdue"),
                            ("STAGE_TARGET_DUE", "Stage target date approaching"),
                            ("STAGE_SUNSET_DUE", "Stage sunset date approaching"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to stop this notification being sent.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "ordering": ["event"],
            },
        ),
        migrations.AddField(
            model_name="councilcontact",
            name="receives_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Tick to send this contact the automated notices for their council (payment released, agreement signed, report decisions, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notifications_from_email",
            field=models.EmailField(
                default="noreply@ricd.qld.gov.au",
                help_text='"From" address used for automated notification emails sent by the system.',
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="SentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=40)),
                ("dedupe_key", models.CharField(db_index=True, max_length=255)),
                (
                    "recipients",
                    models.TextField(
                        blank=True, help_text="Comma-separated recipient emails"
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.council",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Notification",
                "ordering": ["-sent_at"],
            },
        ),
    ]
