# Generated by Django 5.2.12 on 2026-06-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_seed_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email_host",
            field=models.CharField(
                blank=True, help_text="SMTP server hostname", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_host_password",
            field=models.CharField(
                blank=True,
                help_text="SMTP password (optional; stored masked). Leave blank for an unauthenticated relay.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="SMTP username (optional)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_send_mode",
            field=models.CharField(
                choices=[
                    ("LOG", "Log only (do not actually send)"),
                    ("SMTP", "Send via SMTP"),
                ],
                default="LOG",
                help_text="LOG = generate + record but do not send (safe default). SMTP = actually send.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="email_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch — turn ALL automated emails on/off.",
            ),
        ),
    ]
