# Generated by Django 5.2.12 on 2026-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_sitesettings_email_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cashflow_method",
            field=models.CharField(
                choices=[
                    ("MILESTONE", "Capital Grants (Payment Milestone)"),
                    ("WORKSTEP", "Capital Works (WorkStep Progressive)"),
                ],
                db_index=True,
                default="MILESTONE",
                help_text="How this project's cashflow is forecast/accrued: Capital Grants by payment milestone; Capital Works progressively by workstep.",
                max_length=10,
            ),
        ),
    ]
