# Generated by Django 5.2.12 on 2026-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_project_cashflow_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashflowMethodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MILESTONE", "Capital Grants (Payment Milestone)"),
                            ("WORKSTEP", "Capital Works (WorkStep Progressive)"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "accrual_source",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment milestones"),
                            ("WORKSTEP", "WorkStep progressive"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "workstep_date",
                    models.CharField(
                        choices=[
                            ("FCOMP", "Forecast completion date"),
                            ("FSTART", "Forecast start date"),
                        ],
                        default="FCOMP",
                        help_text="Which workstep date forecasts the accrual (actuals always use the actual completion date). Only used when accrual is via worksteps.",
                        max_length=10,
                    ),
                ),
                (
                    "cost_basis",
                    models.CharField(
                        choices=[
                            (
                                "EFFECTIVE",
                                "Effective (actual where entered, else estimated)",
                            ),
                            ("ESTIMATED", "Estimated only"),
                        ],
                        default="EFFECTIVE",
                        help_text="Value base for a workstep's share of the work cost. Only used when accrual is via worksteps.",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Cashflow method rule",
                "ordering": ["method"],
            },
        ),
    ]
