# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
        ("land_infra", "0001_initial"),
        ("programs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2025-2026", "2025-2026 (Current)"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                            ("2030-2031", "2030-2031"),
                            ("2031-2032", "2031-2032"),
                            ("2032-2033", "2032-2033"),
                            ("2033-2034", "2033-2034"),
                            ("2034-2035", "2034-2035"),
                            ("2035-2036", "2035-2036"),
                            ("2036-2037", "2036-2037"),
                            ("2037-2038", "2037-2038"),
                            ("2038-2039", "2038-2039"),
                            ("2039-2040", "2039-2040"),
                        ],
                        default="2025-2026",
                        help_text="Expected financial year for funding",
                        max_length=9,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "funding_approval_date",
                    models.DateField(
                        blank=True, help_text="Date funding was approved", null=True
                    ),
                ),
                ("stage1_target_date", models.DateField(blank=True, null=True)),
                ("stage2_target_date", models.DateField(blank=True, null=True)),
                ("stage1_sunset_date", models.DateField(blank=True, null=True)),
                ("stage2_sunset_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROS", "Prospective"),
                            ("PROG", "Programmed"),
                            ("FUND", "Funded"),
                            ("COMM", "Commenced"),
                            ("UC", "Under Construction"),
                            ("COMP", "Completed"),
                        ],
                        db_index=True,
                        default="PROS",
                        max_length=4,
                    ),
                ),
                (
                    "dwelling_status",
                    models.CharField(
                        choices=[
                            ("PROS", "Prospective"),
                            ("PROG", "Programmed"),
                            ("FUND", "Funded"),
                            ("COMM", "Commenced"),
                            ("WU", "Works Underway"),
                            ("COMP", "Completed"),
                        ],
                        db_index=True,
                        default="PROS",
                        max_length=4,
                    ),
                ),
                (
                    "status_flag",
                    models.CharField(
                        choices=[("ON", "On track"), ("LA", "Late"), ("OV", "Overdue")],
                        db_index=True,
                        default="ON",
                        max_length=2,
                    ),
                ),
                (
                    "lease_signed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date lease was signed (only for non-registered housing providers)",
                        null=True,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("handover_checklist_link", models.URLField(blank=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="councils.council",
                    ),
                ),
                (
                    "land_parcels",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="land_infra.landtenure"
                    ),
                ),
                (
                    "land_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to completed land/infra project that this dwelling is built on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dwelling_projects",
                        to="land_infra.landproject",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="programs.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users"),
                            ("FNC_ONLY", "FNC Users Only"),
                            ("COUNCIL_ONLY", "Council Users Only"),
                            ("PROJECT_TEAM", "Project Team Only"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Internal notes not visible to council"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
