# Generated by Django 5.2.12 on 2026-04-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="financial_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2025-2026", "2025-2026 (Current)"),
                    ("2026-2027", "2026-2027"),
                    ("2027-2028", "2027-2028"),
                    ("2028-2029", "2028-2029"),
                    ("2029-2030", "2029-2030"),
                    ("2030-2031", "2030-2031"),
                    ("2031-2032", "2031-2032"),
                    ("2032-2033", "2032-2033"),
                    ("2033-2034", "2033-2034"),
                    ("2034-2035", "2034-2035"),
                    ("2035-2036", "2035-2036"),
                    ("2036-2037", "2036-2037"),
                    ("2037-2038", "2037-2038"),
                    ("2038-2039", "2038-2039"),
                    ("2039-2040", "2039-2040"),
                ],
                default="",
                help_text="Expected financial year for funding (add later when funding confirmed)",
                max_length=9,
            ),
        ),
    ]
