# Generated by Django 5.2.12 on 2026-04-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_financial_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("DWELLING", "Dwelling"), ("LAND", "Land")],
                db_index=True,
                default="DWELLING",
                max_length=10,
            ),
        ),
    ]
