# Generated by Django 5.2.12 on 2026-04-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("land_infra", "0002_initial"),
        ("projects", "0003_project_project_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="land_project",
        ),
        migrations.AddField(
            model_name="project",
            name="development_application",
            field=models.ForeignKey(
                blank=True,
                help_text="Development application for land projects",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_project",
                to="land_infra.developmentapplication",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="infra_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="infra_electricity_assessment",
            field=models.TextField(
                blank=True,
                help_text="Is there sufficient electricity infrastructure? What is the transformer capacity?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="infra_sewerage_assessment",
            field=models.TextField(
                blank=True,
                help_text="Is there sufficient sewerage infrastructure? What is the treatment capacity?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="infra_water_assessment",
            field=models.TextField(
                blank=True,
                help_text="Is there sufficient water infrastructure? What is the connection capacity?",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="parent_land_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to parent LAND project this dwelling is built on (DWELLING only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_dwellings",
                to="projects.project",
            ),
        ),
    ]
