# Generated by Django 5.2.12 on 2026-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_land_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dwelling_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PROS", "Prospective"),
                    ("PROG", "Programmed"),
                    ("FUND", "Funded"),
                    ("COMM", "Commenced"),
                    ("WU", "Works Underway"),
                    ("COMP", "Completed"),
                ],
                db_index=True,
                default=None,
                max_length=4,
                null=True,
            ),
        ),
    ]
