# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2025-2026", "2025-2026 (Current)"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                            ("2030-2031", "2030-2031"),
                            ("2031-2032", "2031-2032"),
                            ("2032-2033", "2032-2033"),
                            ("2033-2034", "2033-2034"),
                            ("2034-2035", "2034-2035"),
                            ("2035-2036", "2035-2036"),
                            ("2036-2037", "2036-2037"),
                            ("2037-2038", "2037-2038"),
                            ("2038-2039", "2038-2039"),
                            ("2039-2040", "2039-2040"),
                        ],
                        default="2025-2026",
                        help_text="Expected financial year",
                        max_length=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROS", "Prospective"),
                            ("PROG", "Programmed"),
                            ("FUND", "Funded"),
                            ("COMM", "Commenced"),
                            ("WU", "Works Underway"),
                            ("COMP", "Completed"),
                        ],
                        default="PROS",
                        max_length=4,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "infra_water_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Is there sufficient water infrastructure to support the project? What is the connection capacity?",
                    ),
                ),
                (
                    "infra_electricity_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Is there sufficient electricity infrastructure to support the project? What is the transformer capacity?",
                    ),
                ),
                (
                    "infra_sewerage_assessment",
                    models.TextField(
                        blank=True,
                        help_text="Is there sufficient sewerage infrastructure to support the project? What is the treatment capacity?",
                    ),
                ),
                ("infra_comments", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LandTenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_number", models.CharField(max_length=50)),
                ("plan_number", models.CharField(max_length=50)),
                ("title_reference", models.CharField(blank=True, max_length=100)),
                (
                    "tenure_type",
                    models.CharField(
                        choices=[
                            ("CROWN", "Crown Land"),
                            ("FREEHOLD", "Freehold"),
                            ("LEASEHOLD", "Leasehold"),
                        ],
                        default="CROWN",
                        max_length=10,
                    ),
                ),
                (
                    "native_title_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEARED", "Cleared"),
                            ("IULA", "IULA"),
                            ("24JAA", "24JAA"),
                            ("24KAA", "24KAA"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "native_title_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "cultural_heritage_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("CLEARED", "Cleared")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "cultural_heritage_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_developed", models.BooleanField(default=False)),
                ("developed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["council", "lot_number", "plan_number"],
            },
        ),
        migrations.CreateModel(
            name="DevelopmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("DA", "Development Application"),
                            ("MCU", "Material Change of Use"),
                            ("RAL", "Reconfiguring a Lot"),
                            ("PA", "Preliminary Approval"),
                        ],
                        default="DA",
                        max_length=5,
                    ),
                ),
                ("application_reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREP", "Preparing"),
                            ("SUB", "Submitted"),
                            ("ASSESS", "Under Assessment"),
                            ("APPR", "Approved"),
                            ("REF", "Refused"),
                            ("WD", "Withdrawn"),
                        ],
                        default="PREP",
                        max_length=10,
                    ),
                ),
                ("lodged_date", models.DateField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("lapsing_date", models.DateField(blank=True, null=True)),
                ("decision_notice_link", models.URLField(blank=True)),
                ("conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_applications",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
