# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
        ("land_infra", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentapplication",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="development_applications",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="landproject",
            name="council",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_projects",
                to="councils.council",
            ),
        ),
        migrations.AddField(
            model_name="landproject",
            name="development_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="land_projects",
                to="land_infra.developmentapplication",
            ),
        ),
        migrations.AddField(
            model_name="landtenure",
            name="council",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_tenures",
                to="councils.council",
            ),
        ),
        migrations.AddField(
            model_name="landtenure",
            name="parent_lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent lot if this is a subdivided child parcel",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdivided_lots",
                to="land_infra.landtenure",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="landtenure",
            unique_together={("council", "lot_number", "plan_number")},
        ),
    ]
