# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("SPO", "Senior Project Officer"),
                            ("PPO", "Principal Project Officer"),
                            ("MGR", "Manager"),
                            ("DIR", "Director"),
                            ("ED", "Executive Director"),
                            ("GM", "General Manager"),
                            ("DDG", "Deputy Director-General"),
                            ("DG", "Director-General"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for unlimited (e.g., Director-General)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("DWELLING", "Dwelling/Construction"),
                            ("LAND", "Land/Infrastructure"),
                        ],
                        default="DWELLING",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "contingency",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_funding",
                    models.DecimalField(
                        db_index=True, decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "payment_split",
                    models.CharField(
                        choices=[
                            ("30/60/10", "Standard (30/60/10)"),
                            ("90/10", "Alternative (90/10)"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="30/60/10",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "stage1_target_date",
                    models.DateField(
                        blank=True, help_text="Stage 1 Target Date", null=True
                    ),
                ),
                (
                    "stage2_target_date",
                    models.DateField(
                        blank=True, help_text="Stage 2 Target Date", null=True
                    ),
                ),
                (
                    "stage1_sunset_date",
                    models.DateField(
                        blank=True, help_text="Stage 1 Sunset Date", null=True
                    ),
                ),
                (
                    "stage2_sunset_date",
                    models.DateField(
                        blank=True, help_text="Stage 2 Sunset Date", null=True
                    ),
                ),
                (
                    "contact_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="State contact details: attention, phone, email, address",
                    ),
                ),
                (
                    "scope_of_works",
                    models.TextField(
                        blank=True, help_text="Concatenated scope of works description"
                    ),
                ),
                (
                    "land_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Land details: lot, plan, title_reference, street_address",
                    ),
                ),
                (
                    "notional_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total calculated from notional costs",
                        max_digits=12,
                    ),
                ),
                (
                    "actual_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total from actual costs entered",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_state", models.CharField(max_length=4)),
                ("new_state", models.CharField(max_length=4)),
                ("reason", models.TextField(blank=True)),
                (
                    "change_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_centre",
                    models.CharField(
                        blank=True,
                        help_text="Cost centre code (e.g., 316333)",
                        max_length=50,
                    ),
                ),
                (
                    "gl_code",
                    models.CharField(
                        blank=True, help_text="GL code from program", max_length=50
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True, help_text="Tax code (e.g., GST, FBT)", max_length=20
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Allocated funding amount for this work",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FundingApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_PEER", "Pending Peer Review"),
                            ("PENDING_MGR", "Pending Manager Approval"),
                            ("PENDING_DIR", "Pending Director Approval"),
                            ("PENDING_ED", "Pending Executive Director Approval"),
                            ("PENDING_GM", "Pending General Manager Approval"),
                            ("PENDING_DDG", "Pending Deputy Director-General Approval"),
                            ("PENDING_DG", "Pending Director-General Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "contingency_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "mincor_reference",
                    models.CharField(
                        blank=True, help_text="e.g., MN12345-YYYY", max_length=50
                    ),
                ),
                (
                    "mincor_link",
                    models.URLField(blank=True, help_text="Link to MINCOR system"),
                ),
                ("peer_review_required", models.BooleanField(default=False)),
                ("peer_review_completed", models.DateField(blank=True, null=True)),
                ("sent_to_manager", models.DateField(blank=True, null=True)),
                ("manager_approved", models.DateField(blank=True, null=True)),
                ("sent_to_director", models.DateField(blank=True, null=True)),
                ("director_approved", models.DateField(blank=True, null=True)),
                ("sent_to_ed", models.DateField(blank=True, null=True)),
                ("ed_approved", models.DateField(blank=True, null=True)),
                ("sent_to_gm", models.DateField(blank=True, null=True)),
                ("gm_approved", models.DateField(blank=True, null=True)),
                ("sent_to_ddg", models.DateField(blank=True, null=True)),
                ("ddg_approved", models.DateField(blank=True, null=True)),
                ("sent_to_dg", models.DateField(blank=True, null=True)),
                ("dg_approved", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ddg_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ddg_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dg_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dg_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "director_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dir_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ed_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ed_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gm_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gm_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mgr_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peer_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
