# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
        ("funding", "0001_initial"),
        ("land_infra", "0001_initial"),
        ("projects", "0001_initial"),
        ("works", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingapproval",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="funding_approvals", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="councils",
            field=models.ManyToManyField(
                blank=True,
                help_text="Council participants in this funding agreement",
                related_name="funding_schedules",
                to="councils.council",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="land_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_schedules",
                to="land_infra.landproject",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_schedules",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="works",
            field=models.ManyToManyField(
                blank=True,
                help_text="Works funded by this schedule (for per-work funding)",
                related_name="funding_schedules",
                to="works.work",
            ),
        ),
        migrations.AddField(
            model_name="projectstatelog",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectstatelog",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_logs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="workfunding",
            name="funding_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_fundings",
                to="funding.fundingschedule",
            ),
        ),
        migrations.AddField(
            model_name="workfunding",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_details",
                to="works.work",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workfunding",
            unique_together={("work", "funding_schedule")},
        ),
    ]
