# Generated by Django 5.2.12 on 2026-04-26 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("councils", "0001_initial"),
        ("funding", "0002_initial"),
        ("projects", "0002_alter_project_financial_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("SPLIT", "Milestone Percentage"),
                            ("INVOICE", "Invoice/Expense Claim"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "config_json",
                    models.JSONField(
                        default=dict,
                        help_text="Milestones for SPLIT, requires_approval for INVOICE",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number - increment for new versions",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "-version"],
            },
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="replaces_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Replaced by this schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replacements",
                to="funding.fundingschedule",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="schedule_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="fundingschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY", "Ready for Execution"),
                    ("EXECUTED", "Executed"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("SUPERSEDED", "Superseded"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="BriefFinancialApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funding_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "contingency_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "delegate_level",
                    models.CharField(
                        choices=[
                            ("MGR", "Manager"),
                            ("DIR", "Director"),
                            ("GM", "General Manager"),
                        ],
                        default="MGR",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("mincor_reference", models.CharField(blank=True, max_length=50)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brief_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_approvals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FundingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Agreement name/reference", max_length=255
                    ),
                ),
                ("execution_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CEASED", "Ceased"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "document_uri",
                    models.URLField(
                        blank=True, help_text="Google Drive or OpenDocs link"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_agreements",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="funding_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="funding.fundingagreement",
            ),
        ),
        migrations.AddField(
            model_name="fundingschedule",
            name="payment_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment calculation rule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules",
                to="funding.paymentrule",
            ),
        ),
    ]
