# Generated by Django 5.2.12 on 2026-04-27 00:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0004_fundingnotice_expenseclaim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name (e.g., 'projects.Project')", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(help_text="PK of the entity"),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial"),
                            ("CONTRACT", "Contract"),
                            ("PAYMENT", "Payment"),
                            ("REPORT", "Report"),
                            ("VARIATION", "Variation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("MGR", "Manager"),
                            ("DIR", "Director"),
                            ("GM", "General Manager"),
                            ("DELEGATE", "Delegate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="funding_app_entity__d432eb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                (
                    "action",
                    models.CharField(help_text="CREATE, UPDATE, DELETE", max_length=20),
                ),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="funding_aud_entity__bee3b6_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="funding_aud_timesta_21e2fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("RELEASE_PAYMENT", "Payment Released"),
                            ("EXECUTE_VARIATION", "Variation Executed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form: rationale, external ticket IDs, etc.",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="funding_wor_entity__344f92_idx",
                    )
                ],
            },
        ),
    ]
