# Generated by Django 5.2.12 on 2026-04-27 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0005_approval_auditlog_workflowaction"),
        ("projects", "0003_project_project_type"),
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workfunding",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project allocation (use OR work, not both)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_allocations",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="workfunding",
            name="work",
            field=models.ForeignKey(
                blank=True,
                help_text="Work allocation (use OR project, not both)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_details",
                to="works.work",
            ),
        ),
        migrations.AddConstraint(
            model_name="workfunding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", False), ("work__isnull", True)),
                    models.Q(("project__isnull", True), ("work__isnull", False)),
                    _connector="OR",
                ),
                name="workfunding_project_xor_work",
            ),
        ),
    ]
