# Generated by Django 5.2.12 on 2026-04-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0006_workfunding_project_alter_workfunding_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingschedule",
            name="land_project",
        ),
        migrations.RemoveField(
            model_name="fundingschedule",
            name="project_type",
        ),
    ]
