# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("land_infra", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionalCostSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_inflation_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=3.0,
                        help_text="Default inflation rate percentage for bulk updates",
                        max_digits=5,
                    ),
                ),
                (
                    "current_financial_year",
                    models.CharField(
                        choices=[
                            ("2025-2026", "2025-2026 (Current)"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                            ("2030-2031", "2030-2031"),
                            ("2031-2032", "2031-2032"),
                            ("2032-2033", "2032-2033"),
                            ("2033-2034", "2033-2034"),
                            ("2034-2035", "2034-2035"),
                            ("2035-2036", "2035-2036"),
                            ("2036-2037", "2036-2037"),
                            ("2037-2038", "2037-2038"),
                            ("2038-2039", "2038-2039"),
                            ("2039-2040", "2039-2040"),
                        ],
                        default="2025-2026",
                        help_text="Current active financial year",
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notional Cost Settings",
                "verbose_name_plural": "Notional Cost Settings",
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("EXTENSION", "Extension"),
                            ("DEMOLITION", "Demolition"),
                            ("LAND_DEV", "Land Development"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("PLANNING", "Plan and Prepare/Consultant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "has_bedrooms",
                    models.BooleanField(
                        default=False,
                        help_text="Does this work type use bedroom counts?",
                    ),
                ),
                (
                    "default_bedrooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Default bedrooms for this work type"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Work Types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkStepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_templates",
                        to="works.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("DWELLING", "Dwelling/Construction"),
                            ("LAND", "Land/Infrastructure"),
                        ],
                        default="DWELLING",
                        max_length=10,
                    ),
                ),
                ("work_type_other", models.CharField(blank=True, max_length=100)),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of bedrooms (0 if not applicable)"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "is_notional_cost",
                    models.BooleanField(
                        default=True,
                        help_text="If True, cost is calculated from notional rates. If False, use actual_cost.",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual cost (manual override)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="addresses.address",
                    ),
                ),
                (
                    "land_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="land_infra.landproject",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="projects.project",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="works",
                        to="works.worktype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotionalCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2025-2026", "2025-2026 (Current)"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                            ("2030-2031", "2030-2031"),
                            ("2031-2032", "2031-2032"),
                            ("2032-2033", "2032-2033"),
                            ("2033-2034", "2033-2034"),
                            ("2034-2035", "2034-2035"),
                            ("2035-2036", "2035-2036"),
                            ("2036-2037", "2036-2037"),
                            ("2037-2038", "2037-2038"),
                            ("2038-2039", "2038-2039"),
                            ("2039-2040", "2039-2040"),
                        ],
                        default="2025-2026",
                        help_text="Financial year",
                        max_length=9,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per unit/lot/bedroom",
                        max_digits=14,
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of bedrooms (null/0 for work types without bedrooms)",
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the default for this work type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="works.worktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notional Cost",
                "verbose_name_plural": "Notional Costs",
                "ordering": [
                    "financial_year",
                    "work_type__category",
                    "work_type__name",
                ],
                "unique_together": {("work_type", "financial_year", "bedrooms")},
            },
        ),
    ]
