# Generated by Django 5.2.12 on 2026-04-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_land_project_and_more"),
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="land_project",
        ),
        migrations.RemoveField(
            model_name="work",
            name="project_type",
        ),
        migrations.AlterField(
            model_name="work",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="projects.project",
            ),
        ),
    ]
