# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Council",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("region", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "state_electorate",
                    models.CharField(
                        blank=True, help_text="State Electorate", max_length=100
                    ),
                ),
                (
                    "federal_electorate",
                    models.CharField(
                        blank=True, help_text="Federal Electorate", max_length=100
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "is_registered_housing_provider",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "rcpa_contact_name",
                    models.CharField(
                        blank=True, help_text="RCPA contact name", max_length=255
                    ),
                ),
                (
                    "rcpa_contact_phone",
                    models.CharField(
                        blank=True, help_text="RCPA contact phone", max_length=50
                    ),
                ),
                (
                    "rcpa_contact_email",
                    models.EmailField(
                        blank=True, help_text="RCPA contact email", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CouncilContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="councils.council",
                    ),
                ),
            ],
        ),
    ]
