# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("CARPENTER", "Carpenter"),
                            ("BUILDER", "Builder"),
                            ("ELECTRICIAN", "Electrician"),
                            ("PLUMBER", "Plumber"),
                            ("CONCRETER", "Concreter"),
                            ("LANDSCAPER", "Landscaper"),
                            ("CIVIL_ENGINEER", "Civil Engineer"),
                            ("EARTHWORKS", "Earthworks"),
                            ("PAINTER", "Painter"),
                            ("ROOFER", "Roofing"),
                            ("TILER", "Tiler"),
                            ("BRICKLAYER", "Bricklayer"),
                            ("PLANNER", "Town Planner/Urban Planner"),
                            ("ARCHITECT", "Architect"),
                            ("SURVEYOR", "Surveyor"),
                            ("ENGINEER", "Engineer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("licence_number", models.CharField(blank=True, max_length=100)),
                ("licence_expiry", models.DateField(blank=True, null=True)),
                ("abn", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractors",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "ordering": ["council", "company_name"],
                "unique_together": {("council", "company_name", "trade_type")},
            },
        ),
    ]
