# Generated by Django 5.2.6 on 2025-09-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abn', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_source', models.CharField(blank=True, choices=[('Commonwealth', 'Commonwealth'), ('State', 'State')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ricd.council')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_schedule_number', models.IntegerField()),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contingency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('first_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('first_release_date', models.DateField(blank=True, null=True)),
                ('first_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('second_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('second_release_date', models.DateField(blank=True, null=True)),
                ('second_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('third_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('third_release_date', models.DateField(blank=True, null=True)),
                ('third_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_schedules', to='ricd.council')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_schedules', to='ricd.program')),
            ],
            options={
                'unique_together': {('council', 'funding_schedule_number')},
            },
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid', models.BooleanField(default=False)),
                ('funding_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='ricd.fundingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('funding_schedule_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contingency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('principal_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('senior_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('stage1_target', models.DateField(blank=True, null=True)),
                ('stage1_sunset', models.DateField(blank=True, null=True)),
                ('stage2_target', models.DateField(blank=True, null=True)),
                ('stage2_sunset', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('prospective', 'Prospective'), ('programmed', 'Programmed'), ('funded', 'Funded'), ('commenced', 'Commenced'), ('under_construction', 'Under Construction'), ('completed', 'Completed')], default='prospective', max_length=30)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ricd.council')),
                ('funding_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ricd.fundingschedule')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ricd.program')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('progress_notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trackers', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('state', models.CharField(default='QLD', max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reports', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stage1Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage1_reports', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stage2Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage2_reports', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='StageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2')])),
                ('submission_date', models.DateField()),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('checklist', models.JSONField(default=dict)),
                ('funding_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_reports', to='ricd.fundingschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(blank=True, max_length=500, null=True)),
                ('work_type', models.CharField(choices=[('construction', 'Construction'), ('land_lot_development', 'Land Lot Development'), ('demolition', 'Demolition'), ('extension', 'Extension'), ('other', 'Other')], max_length=50)),
                ('output_type', models.CharField(choices=[('detached_house', 'Detached House'), ('unit', 'Self-contained Unit'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('townhouse', 'Townhouse'), ('extension', 'Extension'), ('cluster_house', 'Cluster House')], max_length=50)),
                ('output_quantity', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('kitchens', models.IntegerField(blank=True, null=True)),
                ('dwellings_count', models.IntegerField(default=1)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('identified_date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='ricd.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='ricd.work')),
            ],
        ),
    ]
