# Generated by Django 5.2.6 on 2025-09-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='default_state',
            field=models.CharField(default='QLD', max_length=3),
        ),
        migrations.AddField(
            model_name='council',
            name='default_suburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
