# Generated by Django 5.2.6 on 2025-09-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0002_council_default_postcode_council_default_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instalment',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
