# Generated by Django 5.2.6 on 2025-09-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0003_instalment_payment_reference_instalment_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWorkStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('construction', 'Construction'), ('land_lot_development', 'Land Lot Development'), ('demolition', 'Demolition'), ('extension', 'Extension'), ('other', 'Other')], max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_offset_days', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=models.CASCADE, related_name='default_work_steps', to='ricd.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=models.CASCADE, related_name='work_steps', to='ricd.work')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]