# Generated by Django 5.2.6 on 2025-09-09 00:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0004_workstep_defaultworkstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('construction_stage1', 'Construction Stage 1'), ('land_stage1', 'Land Stage 1'), ('construction_stage2', 'Construction Stage 2'), ('land_stage2', 'Land Stage 2')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('required_evidence', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('state_accepted', models.BooleanField(default=False)),
                ('state_acceptance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['task_type', 'order'],
            },
        ),
        migrations.RenameField(
            model_name='quarterlyreport',
            old_name='summary',
            new_name='summary_notes',
        ),
        migrations.RenameField(
            model_name='stage1report',
            old_name='notes',
            new_name='completion_notes',
        ),
        migrations.RenameField(
            model_name='stage2report',
            old_name='notes',
            new_name='completion_notes',
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='carpentry_2nd_fix_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='carpentry_3rd_fix_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='clothesline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='construction_award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='construction_tender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='design_award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='design_tender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='driveway_paths_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='earthworks_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='electrical_fit_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='end_of_year_shutdown',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='ergon_connection_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='ergon_connection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='external_decks_stairs_balustrade_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='external_doors_windows_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='external_painting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='fascia_gutter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='fencing_gates_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='final_internal_clean_handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='internal_floor_coverings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='internal_painting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='internal_wall_ceiling_linings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='joinery_install_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='plumbing_electrical_rough_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='plumbing_fit_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='roof_framing_battens_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='roof_sheeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='shed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='site_clean_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='site_establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='slab_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='soffit_linings_gables_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='sub_floor_framing_concrete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='termite_prevention_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='underground_services_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='wall_frames_masonry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='waterproofing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='wet_area_wall_linings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='adverse_matters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='comments_indigenous_employment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='council_contributions_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='council_contributions_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='other_contributions_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='other_contributions_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='percentage_works_completed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='practical_completion_actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='practical_completion_forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='total_employed_people',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='total_expenditure_council',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='total_indigenous_employed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='unspent_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='building_approval_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/building_approval/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='building_approval_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='contractor_appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='contractor_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='council_contractors_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='design_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='design_document_approved',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/design/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='design_document_proposed',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/design/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='development_approval_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/dev_approval/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='development_approval_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='expenditure_records_maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='heritage_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/heritage/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='heritage_matters_addressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='infrastructure_approvals_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='infrastructure_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/infrastructure/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='land_description_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/land/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='land_surveyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='land_title_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/land_title/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='native_title_addressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='native_title_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/native_title/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='quarterly_reports_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='report_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('land', 'Land')], default='construction', max_length=20),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='state_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='structural_certification_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/structural/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='structural_certification_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='subdivision_plan_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/subdivision/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='subdivision_plan_prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='subdivision_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='survey_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/survey/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='tenders_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='tenure_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/tenure/'),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='tenure_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='works_description_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/works/'),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='final_plans_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/plans/'),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='final_plans_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='handover_checklist_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='handover_checklist_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/handover/'),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='handover_requirements_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='joint_inspection_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='joint_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='land_works_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='monthly_trackers_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='practical_completion_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='practical_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='practical_completion_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='quarterly_reports_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='report_type',
            field=models.CharField(choices=[('construction', 'Construction'), ('land', 'Land')], default='construction', max_length=20),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='schedule_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='schedule_provided_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='state_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='warranties_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/warranties/'),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='warranties_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultworkstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PracticalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notified_to_state', models.BooleanField(default=False)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('state_acknowledged', models.BooleanField(default=False)),
                ('acknowledgment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_completions', to='ricd.project')),
            ],
        ),
        migrations.CreateModel(
            name='StepTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('evidence_notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='ricd.project')),
                ('step_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='ricd.steptask')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/attachments/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('quarterly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ricd.quarterlyreport')),
                ('step_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ricd.steptaskcompletion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='ricd.project')),
            ],
        ),
    ]
