# Generated by Django 5.2.6 on 2025-09-09 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0005_steptask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytracker',
            name='project',
        ),
        migrations.RemoveField(
            model_name='quarterlyreport',
            name='project',
        ),
        migrations.AddField(
            model_name='monthlytracker',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trackers', to='ricd.work'),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reports', to='ricd.work'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='monthly_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ricd.monthlytracker'),
        ),
        migrations.AlterField(
            model_name='monthlytracker',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.CharField(default='', max_length=20),
        ),
    ]
