# Generated by Django 5.2.6 on 2025-09-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0006_remove_monthlytracker_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='federal_electorate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='qhigi_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='state_electorate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cli_no',
            field=models.CharField(blank=True, help_text='CLI Number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_loa_actual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='commencement_loa_forecast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='commitments',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Funding obtained (10% more than forecast)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, choices=[('council', 'Council'), ('qbuild', 'QBuild'), ('third_party', 'Third Party Contractor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='costs_finalised',
            field=models.BooleanField(default=False, help_text='Yes/No for finalised costs'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_physically_commenced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='handover_actual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='handover_forecast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(blank=True, choices=[('council', 'Council'), ('qbuild', 'QBuild'), ('external', 'External Project Manager')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sap_master_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sap_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='additional_facilities',
            field=models.CharField(blank=True, help_text='Additional WC/BATHROOM', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='car_accommodation',
            field=models.CharField(blank=True, help_text='Carport/Garage/Under House', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='extension_high_low',
            field=models.CharField(blank=True, help_text='High set/Low set for extensions', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='external_wall_method',
            field=models.CharField(blank=True, help_text='Timber/Sheeting/Block/Brick', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='floor_method',
            field=models.CharField(blank=True, help_text='Concrete Slab/Timber Frame/Steel Frame', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='frame_method',
            field=models.CharField(blank=True, help_text='Timber Frame/Steel Frame/Block/FC Panel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='land_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='roof_method',
            field=models.CharField(blank=True, help_text='Metal Sheeting/Tiles/Galv.Sheeting/Colourbond', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sap_project'], name='ricd_projec_sap_pro_92ee9e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['contractor'], name='ricd_projec_contrac_b0e31a_idx'),
        ),
    ]
