# Generated by Django 5.2.6 on 2025-09-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0007_council_federal_electorate_council_lga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='lga',
        ),
        migrations.AddField(
            model_name='address',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='plan_number',
            field=models.CharField(blank=True, help_text='e.g., RP3435', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='title_reference',
            field=models.CharField(blank=True, help_text='e.g., 5456565', max_length=50, null=True),
        ),
    ]
