# Generated by Django 5.2.6 on 2025-09-09 01:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0008_remove_council_lga_address_lot_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingschedule',
            name='second_payment_amount',
        ),
        migrations.RemoveField(
            model_name='fundingschedule',
            name='second_reference_number',
        ),
        migrations.RemoveField(
            model_name='fundingschedule',
            name='second_release_date',
        ),
        migrations.RemoveField(
            model_name='fundingschedule',
            name='third_payment_amount',
        ),
        migrations.RemoveField(
            model_name='fundingschedule',
            name='third_reference_number',
        ),
        migrations.RemoveField(
            model_name='fundingschedule',
            name='third_release_date',
        ),
        migrations.AddField(
            model_name='project',
            name='contingency_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Contingency percentage (default 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_organisation',
            field=models.CharField(blank=True, help_text='Name of third party contractor organisation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='external_manager_name',
            field=models.CharField(blank=True, help_text='Name of external project manager', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='contingency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contingency amount (calculated or manual)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total funding amount allocated', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='commitments',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total funding obtained', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ricd.fundingschedule'),
        ),
    ]
