# Generated by Django 5.2.6 on 2025-09-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0009_remove_fundingschedule_second_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='resolved',
        ),
        migrations.AddField(
            model_name='defect',
            name='rectified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
