# Generated by Django 5.2.6 on 2025-09-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mincor_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_by', models.CharField(max_length=255)),
                ('approved_date', models.DateField()),
                ('projects', models.ManyToManyField(related_name='funding_approvals', to='ricd.project')),
            ],
            options={
                'ordering': ['-approved_date'],
            },
        ),
        migrations.CreateModel(
            name='CouncilQuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the quarter, e.g., Jan 1, Apr 1, Jul 1, Oct 1')),
                ('council_comments', models.TextField(blank=True)),
                ('ricd_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('more_info', 'More Info Requested')], default='more_info', max_length=20)),
                ('ricd_comments', models.TextField(blank=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_quarterly_reports', to='ricd.council')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('council', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month')),
                ('council_comments', models.TextField(blank=True)),
                ('ricd_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('more_info', 'More Info Requested')], default='more_info', max_length=20)),
                ('ricd_comments', models.TextField(blank=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='ricd.council')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('council', 'period')},
            },
        ),
    ]
