# Generated by Django 5.2.6 on 2025-09-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0012_fundingapproval_councilquarterlyreport_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyreport',
            name='supporting_document_1',
            field=models.FileField(blank=True, help_text='Supporting document 1', null=True, upload_to='reports/supporting/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='supporting_document_2',
            field=models.FileField(blank=True, help_text='Supporting document 2', null=True, upload_to='reports/supporting/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='supporting_document_3',
            field=models.FileField(blank=True, help_text='Supporting document 3', null=True, upload_to='reports/supporting/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='supporting_document_description',
            field=models.TextField(blank=True, help_text='Description of supporting documents', null=True),
        ),
    ]
