# Generated by Django 5.2.6 on 2025-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0013_quarterlyreport_supporting_document_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['street']},
        ),
        migrations.AddField(
            model_name='address',
            name='bedrooms',
            field=models.IntegerField(blank=True, help_text='Number of bedrooms', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this address', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='output_quantity',
            field=models.IntegerField(default=1, help_text='Number of outputs (e.g., houses, units) at this address'),
        ),
        migrations.AddField(
            model_name='address',
            name='output_type',
            field=models.CharField(blank=True, choices=[('detached_house', 'Detached House'), ('unit', 'Self-contained Unit'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('townhouse', 'Townhouse'), ('extension', 'Extension'), ('cluster_house', 'Cluster House'), ('consultancy', 'Consultancy'), ('other_expenses', 'Other Expenses')], help_text='Type of output at this address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='work_type',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('land_lot_development', 'Land Lot Development'), ('demolition', 'Demolition'), ('extension', 'Extension'), ('other', 'Other')], help_text='Type of work at this address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(help_text='4-digit postcode', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Street address', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(help_text='Suburb/Town', max_length=255),
        ),
    ]
