# Generated by Django 5.2.6 on 2025-09-09 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0016_add_missing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultworkstep',
            name='work_type',
        ),
        migrations.AddField(
            model_name='defaultworkstep',
            name='work_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='default_steps', to='ricd.worktype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='agreement_type',
            field=models.CharField(choices=[('funding_schedule', 'Funding Schedule'), ('frpf_agreement', 'Forward Remote Program Funding Agreement'), ('ifrpf_agreement', 'Interim Forward Remote Program Funding Agreement')], default='funding_schedule', help_text='Type of funding agreement', max_length=20),
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='date_council_signed',
            field=models.DateField(blank=True, help_text='Date council signed the agreement', null=True),
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='date_delegate_signed',
            field=models.DateField(blank=True, help_text='Date delegate signed the agreement', null=True),
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='date_sent_to_council',
            field=models.DateField(blank=True, help_text='Date funding agreement sent to council', null=True),
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='executed_date',
            field=models.DateField(blank=True, help_text='Date agreement was executed (calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='output_type_id',
            field=models.ForeignKey(blank=True, help_text='Type of output at this address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricd.outputtype'),
        ),
        migrations.AlterField(
            model_name='address',
            name='work_type_id',
            field=models.ForeignKey(blank=True, help_text='Type of work at this address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricd.worktype'),
        ),
        migrations.AlterField(
            model_name='work',
            name='output_type_id',
            field=models.ForeignKey(help_text='Type of output/tenure to be produced', on_delete=django.db.models.deletion.PROTECT, to='ricd.outputtype'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type_id',
            field=models.ForeignKey(help_text='Type of work to be performed', on_delete=django.db.models.deletion.PROTECT, to='ricd.worktype'),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text='Official position title', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this officer is active')),
                ('is_principal', models.BooleanField(default=False, help_text='Can be assigned as Principal Officer')),
                ('is_senior', models.BooleanField(default=False, help_text='Can be assigned as Senior Officer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_projects', to='ricd.officer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='senior_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_projects', to='ricd.officer'),
        ),
    ]
