# Generated by Django 5.2.6 on 2025-09-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0017_remove_defaultworkstep_work_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardRemoteProgramFundingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent_to_council', models.DateField(blank=True, help_text='Date funding agreement sent to council', null=True)),
                ('date_council_signed', models.DateField(blank=True, help_text='Date council signed the agreement', null=True)),
                ('date_delegate_signed', models.DateField(blank=True, help_text='Date delegate signed the agreement', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterimForwardProgramFundingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent_to_council', models.DateField(blank=True, help_text='Date funding agreement sent to council', null=True)),
                ('date_council_signed', models.DateField(blank=True, help_text='Date council signed the agreement', null=True)),
                ('date_delegate_signed', models.DateField(blank=True, help_text='Date delegate signed the agreement', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fundingapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='work',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='work',
            name='project',
        ),
        migrations.AddField(
            model_name='council',
            name='default_principal_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_principal_defaults', to='ricd.officer'),
        ),
        migrations.AddField(
            model_name='council',
            name='default_senior_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_senior_defaults', to='ricd.officer'),
        ),
        migrations.AddField(
            model_name='fundingapproval',
            name='approved_by_position',
            field=models.CharField(default='director-general', help_text='Position/role that approved', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='manager_comments',
            field=models.TextField(blank=True, help_text='RICD Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='RICD Manager approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='manager_decision_date',
            field=models.DateField(blank=True, help_text='Date of RICD Manager decision', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='staff_assessed_date',
            field=models.DateField(blank=True, help_text='Date when RICD Staff assessed', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='staff_assessment_notes',
            field=models.TextField(blank=True, help_text='RICD Staff assessment notes', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='ricd.address'),
        ),
        migrations.AddField(
            model_name='project',
            name='forward_rpf_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ricd.forwardremoteprogramfundingagreement'),
        ),
        migrations.AddField(
            model_name='project',
            name='interim_fp_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='ricd.interimforwardprogramfundingagreement'),
        ),
    ]
