# Generated by Django 4.2.7 on 2025-09-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0018_forwardremoteprogramfundingagreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteCapitalProgramFundingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent_to_council', models.DateField(blank=True, help_text='Date funding agreement sent to council', null=True)),
                ('date_council_signed', models.DateField(blank=True, help_text='Date council signed the agreement', null=True)),
                ('date_delegate_signed', models.DateField(blank=True, help_text='Date delegate signed the agreement', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the agreement', null=True)),
            ],
            options={
                'verbose_name': 'Remote Capital Program Funding Agreement',
                'verbose_name_plural': 'Remote Capital Program Funding Agreements',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('funding_schedule', 'Funding Schedule'), ('frpf_agreement', 'Forward Remote Program Funding Agreement'), ('ifrpf_agreement', 'Interim Forward Remote Program Funding Agreement'), ('rcpf_agreement', 'Remote Capital Program Funding Agreement')], help_text='Type of agreement being varied', max_length=20)),
                ('agreement_id', models.PositiveIntegerField(help_text='ID of the agreement being varied')),
                ('variation_description', models.TextField(help_text='Description of what was varied')),
                ('variation_date', models.DateField(help_text='Date the variation was made')),
                ('date_sent_to_council', models.DateField(blank=True, help_text='Date variation sent to council', null=True)),
                ('date_council_signed', models.DateField(blank=True, help_text='Date council signed variation', null=True)),
                ('date_delegate_signed', models.DateField(blank=True, help_text='Date delegate signed variation', null=True)),
                ('executed_date', models.DateField(blank=True, help_text='Date variation executed (calculated)', null=True)),
                ('additional_funding', models.DecimalField(blank=True, decimal_places=2, help_text='Additional funding amount', max_digits=15, null=True)),
                ('adjusted_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Adjusted total budget', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the variation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-variation_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='forwardremoteprogramfundingagreement',
            name='council',
            field=models.OneToOneField(help_text='Council this agreement applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_rpf_agreement', to='ricd.council'),
        ),
        migrations.AddField(
            model_name='interimforwardprogramfundingagreement',
            name='council',
            field=models.OneToOneField(help_text='Council this agreement applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interim_fp_agreement', to='ricd.council'),
        ),
        migrations.AddField(
            model_name='project',
            name='cancelled_outputs',
            field=models.PositiveIntegerField(default=0, help_text='Number of outputs cancelled'),
        ),
        migrations.AddField(
            model_name='project',
            name='replacement_funding_schedule',
            field=models.ForeignKey(blank=True, help_text='Replacement or additional funding schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_replacements', to='ricd.fundingschedule'),
        ),
        migrations.AddField(
            model_name='project',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Date project was terminated or cancelled', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for termination or cancellation', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='variation_description',
            field=models.TextField(blank=True, help_text='Description of what was varied', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='varied_outputs',
            field=models.PositiveIntegerField(default=0, help_text='Number of outputs varied'),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='agreement_type',
            field=models.CharField(choices=[('funding_schedule', 'Funding Schedule'), ('frpf_agreement', 'Forward Remote Program Funding Agreement'), ('ifrpf_agreement', 'Interim Forward Remote Program Funding Agreement'), ('rcpf_agreement', 'Remote Capital Program Funding Agreement')], default='funding_schedule', help_text='Type of funding agreement', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('prospective', 'Prospective'), ('programmed', 'Programmed'), ('funded', 'Funded'), ('commenced', 'Commenced'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('varied', 'Varied')], default='prospective', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='ricd.address'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['state'], name='ricd_projec_state_f43059_idx'),
        ),
        migrations.AddField(
            model_name='variation',
            name='replacement_funding_schedule',
            field=models.ForeignKey(blank=True, help_text='Replacement or additional funding schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation_replacements', to='ricd.fundingschedule'),
        ),
        migrations.AddField(
            model_name='remotecapitalprogramfundingagreement',
            name='council',
            field=models.OneToOneField(help_text='Council this agreement applies to', on_delete=django.db.models.deletion.CASCADE, related_name='remote_capital_program_agreement', to='ricd.council'),
        ),
        migrations.AddField(
            model_name='remotecapitalprogramfundingagreement',
            name='funding_schedules',
            field=models.ManyToManyField(blank=True, help_text='Funding schedules under this program agreement', related_name='remote_capital_program_agreements', to='ricd.fundingschedule'),
        ),
        migrations.AddField(
            model_name='fundingschedule',
            name='remote_capital_program',
            field=models.ForeignKey(blank=True, help_text='Remote Capital Program Funding Agreement this schedule belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_funding', to='ricd.remotecapitalprogramfundingagreement'),
        ),
    ]
