# Generated by Django 4.2.7 on 2025-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0019_remotecapitalprogramfundingagreement_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='construction_method',
            field=models.CharField(blank=True, choices=[('on_site', 'On Site'), ('flatpack', 'Flatpack'), ('modern_methods_of_construction', 'Modern Methods of Construction'), ('pre_built', 'Pre-built'), ('offsite', 'Offsite')], help_text='Construction method used for this address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='construction_method',
            field=models.CharField(blank=True, choices=[('on_site', 'On Site'), ('flatpack', 'Flatpack'), ('modern_methods_of_construction', 'Modern Methods of Construction'), ('pre_built', 'Pre-built'), ('offsite', 'Offsite')], help_text='Construction method used for this work', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='allowed_output_types',
            field=models.ManyToManyField(blank=True, help_text='Output types that are allowed for this work type', related_name='work_types', to='ricd.outputtype'),
        ),
    ]
