# Generated by Django 4.2.7 on 2025-09-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0020_address_construction_method_work_construction_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code for construction method', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for construction method', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='address',
            name='construction_method',
            field=models.ForeignKey(blank=True, help_text='Construction method used for this address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricd.constructionmethod'),
        ),
        migrations.AlterField(
            model_name='work',
            name='construction_method',
            field=models.ForeignKey(blank=True, help_text='Construction method used for this work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricd.constructionmethod'),
        ),
    ]
