# Generated by Django 4.2.7 on 2025-09-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0022_alter_work_construction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='construction_method',
            field=models.ForeignKey(blank=True, help_text='Construction method used for this work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ricd.constructionmethod'),
        ),
    ]
