# Generated by Django 4.2.7 on 2025-09-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0023_alter_work_construction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='council_manager_comments',
            field=models.TextField(blank=True, help_text='Council Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='council_manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Council Manager approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='council_manager_decision_date',
            field=models.DateField(blank=True, help_text='Date of Council Manager decision', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='council_manager_comments',
            field=models.TextField(blank=True, help_text='Council Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='council_manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Council Manager approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='quarterlyreport',
            name='council_manager_decision_date',
            field=models.DateField(blank=True, help_text='Date of Council Manager decision', null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='council_manager_comments',
            field=models.TextField(blank=True, help_text='Council Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='council_manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Council Manager approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='council_manager_decision_date',
            field=models.DateField(blank=True, help_text='Date of Council Manager decision', null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='council_manager_comments',
            field=models.TextField(blank=True, help_text='Council Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='council_manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Council Manager approval decision', max_length=10),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='council_manager_decision_date',
            field=models.DateField(blank=True, help_text='Date of Council Manager decision', null=True),
        ),
    ]
