# Generated by Django 4.2.7 on 2025-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0024_monthlyreport_council_manager_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='council_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('user', 'User')], help_text='Role within the council (Manager or User)', max_length=20, null=True),
        ),
    ]
