# Generated by Django 4.2.7 on 2025-09-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0026_add_field_visibility_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFieldVisibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('commitments', 'Commitments'), ('contingency_amount', 'Contingency Amount'), ('forecast_final_cost', 'Forecast Final Cost'), ('final_cost', 'Final Cost'), ('costs_finalised', 'Costs Finalised'), ('project_manager', 'Project Manager'), ('contractor', 'Contractor'), ('contractor_address', 'Contractor Address'), ('external_manager_name', 'External Manager Name'), ('contractor_organisation', 'Contractor Organisation'), ('sap_project', 'SAP Project'), ('cli_no', 'CLI Number'), ('sap_master_project', 'SAP Master Project'), ('handover_forecast', 'Handover Forecast Date'), ('handover_actual', 'Handover Actual Date'), ('actual_completion', 'Actual Completion Date'), ('estimated_completion', 'Estimated Completion Date'), ('termination_date', 'Termination Date'), ('termination_reason', 'Termination Reason'), ('variation_description', 'Variation Description')], help_text='The field to control visibility for', max_length=50)),
                ('visible_to_council_users', models.BooleanField(help_text='Whether this field is visible to Council Users for this specific project')),
                ('project', models.ForeignKey(help_text='Project these settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='field_visibility_overrides', to='ricd.project')),
            ],
            options={
                'verbose_name': 'Project Field Visibility Override',
                'verbose_name_plural': 'Project Field Visibility Overrides',
                'unique_together': {('project', 'field_name')},
            },
        ),
    ]
