# Generated by Django 4.2.7 on 2025-09-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0027_projectfieldvisibilityoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTrackerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the tracker item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this tracker item measures', null=True)),
                ('data_type', models.CharField(choices=[('date', 'Date'), ('checkbox', 'Checkbox'), ('text', 'Text Input'), ('number', 'Number'), ('currency', 'Currency'), ('dropdown', 'Dropdown')], default='date', help_text='Type of data this tracker item collects', max_length=20)),
                ('dropdown_options', models.TextField(blank=True, help_text="Comma-separated list of options for dropdown type (e.g., 'Yes,No,N/A')", null=True)),
                ('required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('na_acceptable', models.BooleanField(default=True, help_text='Whether N/A is an acceptable value')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in reports')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tracker item is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Tracker Item',
                'verbose_name_plural': 'Monthly Tracker Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTrackerItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tracker item group', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this group', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tracker_items', models.ManyToManyField(help_text='Tracker items included in this group', related_name='groups', to='ricd.monthlytrackeritem')),
            ],
            options={
                'verbose_name': 'Monthly Tracker Item Group',
                'verbose_name_plural': 'Monthly Tracker Item Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the report item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this report item measures', null=True)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('text', 'Text Input'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('yes_no', 'Yes/No')], default='number', help_text='Type of data this report item collects', max_length=20)),
                ('dropdown_options', models.TextField(blank=True, help_text='Comma-separated list of options for dropdown type', null=True)),
                ('required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('na_acceptable', models.BooleanField(default=True, help_text='Whether N/A is an acceptable value')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in reports')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this report item is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quarterly Report Item',
                'verbose_name_plural': 'Quarterly Report Items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage1Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Stage 1 step', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this step', null=True)),
                ('required_evidence', models.TextField(blank=True, help_text='Description of evidence required for this step', null=True)),
                ('document_required', models.BooleanField(default=False, help_text='Whether a document upload is required for this step')),
                ('document_description', models.TextField(blank=True, help_text='Description of what document should be uploaded', null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in reports')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this step is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage 1 Step',
                'verbose_name_plural': 'Stage 1 Steps',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage2Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Stage 2 step', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this step', null=True)),
                ('required_evidence', models.TextField(blank=True, help_text='Description of evidence required for this step', null=True)),
                ('document_required', models.BooleanField(default=False, help_text='Whether a document upload is required for this step')),
                ('document_description', models.TextField(blank=True, help_text='Description of what document should be uploaded', null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in reports')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this step is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage 2 Step',
                'verbose_name_plural': 'Stage 2 Steps',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage2StepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the step group', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this group', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('steps', models.ManyToManyField(help_text='Steps included in this group', related_name='groups', to='ricd.stage2step')),
            ],
            options={
                'verbose_name': 'Stage 2 Step Group',
                'verbose_name_plural': 'Stage 2 Step Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage1StepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the step group', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this group', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('steps', models.ManyToManyField(help_text='Steps included in this group', related_name='groups', to='ricd.stage1step')),
            ],
            options={
                'verbose_name': 'Stage 1 Step Group',
                'verbose_name_plural': 'Stage 1 Step Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReportItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the report item group', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this group', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('report_items', models.ManyToManyField(help_text='Report items included in this group', related_name='groups', to='ricd.quarterlyreportitem')),
            ],
            options={
                'verbose_name': 'Quarterly Report Item Group',
                'verbose_name_plural': 'Quarterly Report Item Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('monthly_tracker_groups', models.ManyToManyField(blank=True, help_text='Monthly tracker item groups applicable to this project', related_name='project_configurations', to='ricd.monthlytrackeritemgroup')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_configuration', to='ricd.project')),
                ('quarterly_report_groups', models.ManyToManyField(blank=True, help_text='Quarterly report item groups applicable to this project', related_name='project_configurations', to='ricd.quarterlyreportitemgroup')),
                ('stage1_step_groups', models.ManyToManyField(blank=True, help_text='Stage 1 step groups applicable to this project', related_name='project_configurations', to='ricd.stage1stepgroup')),
                ('stage2_step_groups', models.ManyToManyField(blank=True, help_text='Stage 2 step groups applicable to this project', related_name='project_configurations', to='ricd.stage2stepgroup')),
            ],
            options={
                'verbose_name': 'Project Report Configuration',
                'verbose_name_plural': 'Project Report Configurations',
            },
        ),
        migrations.CreateModel(
            name='Stage2StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Whether this step is completed')),
                ('completed_date', models.DateField(blank=True, help_text='Date when step was completed', null=True)),
                ('evidence_notes', models.TextField(blank=True, help_text='Notes about evidence provided for this step', null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document for this step', null=True, upload_to='reports/stage2/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stage2_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='ricd.stage2report')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='ricd.stage2step')),
            ],
            options={
                'verbose_name': 'Stage 2 Step Completion',
                'verbose_name_plural': 'Stage 2 Step Completions',
                'unique_together': {('stage2_report', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Stage1StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Whether this step is completed')),
                ('completed_date', models.DateField(blank=True, help_text='Date when step was completed', null=True)),
                ('evidence_notes', models.TextField(blank=True, help_text='Notes about evidence provided for this step', null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document for this step', null=True, upload_to='reports/stage1/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stage1_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='ricd.stage1report')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='ricd.stage1step')),
            ],
            options={
                'verbose_name': 'Stage 1 Step Completion',
                'verbose_name_plural': 'Stage 1 Step Completions',
                'unique_together': {('stage1_report', 'step')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReportItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, help_text='Value for this report item entry', null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document for this entry', null=True, upload_to='reports/quarterly/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('quarterly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_entries', to='ricd.quarterlyreport')),
                ('report_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ricd.quarterlyreportitem')),
            ],
            options={
                'verbose_name': 'Quarterly Report Item Entry',
                'verbose_name_plural': 'Quarterly Report Item Entries',
                'unique_together': {('quarterly_report', 'report_item')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, help_text='Value for this tracker item entry', null=True)),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document for this entry', null=True, upload_to='reports/monthly_tracker/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('monthly_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ricd.monthlytracker')),
                ('tracker_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ricd.monthlytrackeritem')),
            ],
            options={
                'verbose_name': 'Monthly Tracker Entry',
                'verbose_name_plural': 'Monthly Tracker Entries',
                'unique_together': {('monthly_tracker', 'tracker_item')},
            },
        ),
    ]
