# Generated by Django 4.2.7 on 2025-09-16 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricd', '0028_monthlytrackeritem_monthlytrackeritemgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='council_manager_approved',
            field=models.BooleanField(default=False, help_text='Council Manager approval status'),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='council_manager_approved_by',
            field=models.ForeignKey(blank=True, help_text='Council Manager who approved this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_manager_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='council_manager_approved_date',
            field=models.DateTimeField(blank=True, help_text='Date of Council Manager approval', null=True),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='council_manager_comments',
            field=models.TextField(blank=True, help_text='Council Manager comments', null=True),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved',
            field=models.BooleanField(default=False, help_text='RICD Officer approval status'),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved_by',
            field=models.ForeignKey(blank=True, help_text='RICD Officer who approved this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricd_officer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved_date',
            field=models.DateTimeField(blank=True, help_text='Date of RICD Officer approval', null=True),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='ricd_officer_comments',
            field=models.TextField(blank=True, help_text='RICD Officer comments', null=True),
        ),
        migrations.AddField(
            model_name='monthlytrackerentry',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('council_manager', 'Pending Council Manager Approval'), ('ricd_officer', 'Pending RICD Officer Approval'), ('approved', 'Approved')], default='draft', help_text='Current workflow status of this entry', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Overall progress percentage'),
        ),
        migrations.AddField(
            model_name='work',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage for this work'),
        ),
    ]
