# Generated by Django 4.2.7 on 2025-09-29 23:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ricd', '0029_monthlytrackerentry_council_manager_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY (31/12/2023)'), ('MM/DD/YYYY', 'MM/DD/YYYY (12/31/2023)'), ('YYYY-MM-DD', 'YYYY-MM-DD (2023-12-31)'), ('DD MMM YYYY', 'DD MMM YYYY (31 Dec 2023)'), ('MMM DD, YYYY', 'MMM DD, YYYY (Dec 31, 2023)')], default='DD/MM/YYYY', help_text='Default date format for the entire site', max_length=20)),
                ('time_format', models.CharField(choices=[('12H', '12 Hour (2:30 PM)'), ('24H', '24 Hour (14:30)')], default='24H', help_text='Default time format (12H or 24H)', max_length=10)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Australia/Sydney', 'Australia/Sydney'), ('Australia/Melbourne', 'Australia/Melbourne'), ('Australia/Brisbane', 'Australia/Brisbane'), ('Australia/Perth', 'Australia/Perth'), ('Australia/Adelaide', 'Australia/Adelaide'), ('Australia/Darwin', 'Australia/Darwin'), ('Australia/Hobart', 'Australia/Hobart'), ('US/Eastern', 'US/Eastern'), ('US/Central', 'US/Central'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Singapore', 'Asia/Singapore')], default='Australia/Brisbane', help_text='Default timezone for the site', max_length=50)),
                ('default_currency', models.CharField(choices=[('AUD', 'Australian Dollar (AUD)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('CAD', 'Canadian Dollar (CAD)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (CNY)'), ('NZD', 'New Zealand Dollar (NZD)'), ('ZAR', 'South African Rand (ZAR)')], default='AUD', help_text='Default currency for financial displays', max_length=10)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol to display', max_length=5, validators=[django.core.validators.RegexValidator('^.{0,5}$', 'Currency symbol must be 5 characters or less')])),
                ('currency_position', models.CharField(choices=[('before', 'Before amount ($100)'), ('after', 'After amount (100$)')], default='before', help_text='Position of currency symbol', max_length=10)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('en-au', 'English (Australia)'), ('en-us', 'English (US)'), ('en-gb', 'English (UK)')], default='en-au', help_text='Default language for the site', max_length=10)),
                ('decimal_places', models.PositiveIntegerField(default=2, help_text='Default number of decimal places for currency', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('thousands_separator', models.CharField(default=',', help_text='Thousands separator character', max_length=1)),
                ('decimal_separator', models.CharField(default='.', help_text='Decimal separator character', max_length=1)),
                ('enable_dark_mode', models.BooleanField(default=False, help_text='Enable dark mode theme site-wide')),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable animations and transitions')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (shows maintenance page)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to show during maintenance mode', null=True)),
                ('site_title', models.CharField(default='RICD Portal', help_text='Site title displayed in browser and headers', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Site description for SEO and headers', null=True)),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='steptaskcompletion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='steptaskcompletion',
            name='step_task',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='work',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='stage1report',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AlterModelOptions(
            name='stage2report',
            options={'ordering': ['-submission_date']},
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='council_manager_approved',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='council_manager_approved_by',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='council_manager_approved_date',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='council_manager_comments',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved_by',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='ricd_officer_approved_date',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='ricd_officer_comments',
        ),
        migrations.RemoveField(
            model_name='monthlytrackerentry',
            name='workflow_status',
        ),
        migrations.RemoveField(
            model_name='quarterlyreport',
            name='total_employed_people',
        ),
        migrations.RemoveField(
            model_name='quarterlyreport',
            name='total_indigenous_employed',
        ),
        migrations.RemoveField(
            model_name='stage1report',
            name='acceptance_date',
        ),
        migrations.RemoveField(
            model_name='stage1report',
            name='council_manager_comments',
        ),
        migrations.RemoveField(
            model_name='stage1report',
            name='council_manager_decision',
        ),
        migrations.RemoveField(
            model_name='stage1report',
            name='council_manager_decision_date',
        ),
        migrations.RemoveField(
            model_name='stage1report',
            name='state_accepted',
        ),
        migrations.RemoveField(
            model_name='stage2report',
            name='acceptance_date',
        ),
        migrations.RemoveField(
            model_name='stage2report',
            name='council_manager_decision_date',
        ),
        migrations.RemoveField(
            model_name='stage2report',
            name='state_accepted',
        ),
        migrations.AddField(
            model_name='stage1report',
            name='ricd_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage1report',
            name='ricd_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Information')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='ricd_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage2report',
            name='ricd_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Information')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this address', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='address',
            name='output_quantity',
            field=models.IntegerField(default=1, help_text='Number of outputs (e.g., houses, units) at this address', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(help_text='4-digit postcode', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Postcode must be exactly 4 digits')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='title_reference',
            field=models.CharField(blank=True, help_text='e.g., 5456565', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d*$', 'Title reference must be numeric')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?61\\s?\\d{3}[\\s\\-]?\\d{3}[\\s\\-]?\\d{3}$|^\\d{8,10}$', 'Phone number must be a valid Australian phone number (e.g., +61 7 1234 5678 or 0412345678)')]),
        ),
        migrations.AlterField(
            model_name='council',
            name='abn',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'ABN must be exactly 11 digits')]),
        ),
        migrations.AlterField(
            model_name='council',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Postcode must be exactly 4 digits')]),
        ),
        migrations.AlterField(
            model_name='defect',
            name='description',
            field=models.TextField(help_text='Description of the defect'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='identified_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date defect was identified'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='rectified_date',
            field=models.DateField(blank=True, help_text='Date defect was rectified', null=True),
        ),
        migrations.AlterField(
            model_name='fundingapproval',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='contingency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contingency amount (calculated or manual)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='first_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total funding amount allocated', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='fundingschedule',
            name='funding_schedule_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='program',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='cancelled_outputs',
            field=models.PositiveIntegerField(default=0, help_text='Number of outputs cancelled', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='contingency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='contingency_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Contingency percentage (default 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='forecast_final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_schedule_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Overall progress percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='varied_outputs',
            field=models.PositiveIntegerField(default=0, help_text='Number of outputs varied', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='council_contributions_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='other_contributions_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='percentage_works_completed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='total_expenditure_council',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='unspent_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='step_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ricd.stage1stepcompletion'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='building_approval_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='design_document_approved',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='design_document_proposed',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='development_approval_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='heritage_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='infrastructure_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='land_description_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='land_title_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='native_title_documentation',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='structural_certification_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='subdivision_plan_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='survey_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='tenure_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage1report',
            name='works_description_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage1/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='council_manager_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='council_manager_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='final_plans_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='handover_checklist_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stage2report',
            name='warranties_document',
            field=models.FileField(blank=True, null=True, upload_to='reports/stage2/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='additional_funding',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional funding amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='adjusted_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Adjusted total budget', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='agreement_id',
            field=models.PositiveIntegerField(help_text='ID of the agreement being varied', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='work',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='dwellings_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='work',
            name='kitchens',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='output_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage for this work', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='PracticalCompletion',
        ),
        migrations.DeleteModel(
            name='StepTask',
        ),
        migrations.DeleteModel(
            name='StepTaskCompletion',
        ),
        migrations.DeleteModel(
            name='WorkProgress',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
