# Generated by Django 4.2.7 on 2025-10-07 22:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ricd", "0030_add_siteconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramProjectAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="ricd.program",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="ricd.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program-Project Allocation",
                "verbose_name_plural": "Program-Project Allocations",
                "unique_together": {("program", "project")},
            },
        ),
    ]
