# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("councils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("FNC_USER", "FNC User"),
                            ("FNC_MANAGER", "FNC Manager"),
                            ("COUNCIL_USER", "Council User"),
                            ("COUNCIL_MANAGER", "Council Manager"),
                            ("OTHER_TEAM_USER", "HPW Other Team User"),
                            ("OTHER_TEAM_MANAGER", "HPW Other Team Manager"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("can_approve_reports", models.BooleanField(default=False)),
                ("can_approve_payments", models.BooleanField(default=False)),
                ("can_manage_councils", models.BooleanField(default=False)),
                ("can_manage_programs", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fnc_permissions",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("position", models.CharField(blank=True, max_length=100)),
                (
                    "officer_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRINCIPAL_OFFICER", "Principal Officer"),
                            ("SENIOR_OFFICER", "Senior Officer"),
                            ("PROGRAM_OFFICER", "Program Officer"),
                            ("MANAGER", "Manager"),
                            ("DIRECTOR", "Director"),
                            ("COUNCIL_USER", "Council User"),
                            ("COUNCIL_MANAGER", "Council Manager"),
                            ("OTHER", "Other"),
                        ],
                        help_text="FNC role for the officer",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="councils.council",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
