# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("councils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("housing_application_count", models.PositiveIntegerField(default=0)),
                ("bedrooms_needed_1", models.PositiveIntegerField(default=0)),
                ("bedrooms_needed_2", models.PositiveIntegerField(default=0)),
                ("bedrooms_needed_3", models.PositiveIntegerField(default=0)),
                ("bedrooms_needed_4plus", models.PositiveIntegerField(default=0)),
                ("overcrowded_households", models.PositiveIntegerField(default=0)),
                ("additional_bedrooms_needed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategic_plans",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Strategic Plans",
                "ordering": ["-year", "council"],
                "unique_together": {("council", "year")},
            },
        ),
    ]
