# Generated by Django 5.2.12 on 2026-04-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "funding_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMMONWEALTH", "Commonwealth Government"),
                            ("STATE", "State Budget"),
                            ("COMMONWEALTH_STATE", "Commonwealth & State Joint"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "funding_source_other",
                    models.CharField(
                        blank=True, help_text="If 'Other' is selected", max_length=255
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total budget (use budgets below for year-specific)",
                        max_digits=14,
                    ),
                ),
                (
                    "gl_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "business_case_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        choices=[
                            ("2025-2026", "2025-2026 (Current)"),
                            ("2026-2027", "2026-2027"),
                            ("2027-2028", "2027-2028"),
                            ("2028-2029", "2028-2029"),
                            ("2029-2030", "2029-2030"),
                            ("2030-2031", "2030-2031"),
                            ("2031-2032", "2031-2032"),
                            ("2032-2033", "2032-2033"),
                            ("2033-2034", "2033-2034"),
                            ("2034-2035", "2034-2035"),
                            ("2035-2036", "2035-2036"),
                            ("2036-2037", "2036-2037"),
                            ("2037-2038", "2037-2038"),
                            ("2038-2039", "2038-2039"),
                            ("2039-2040", "2039-2040"),
                        ],
                        default="2025-2026",
                        max_length=9,
                    ),
                ),
                (
                    "allocated",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget allocated for this year",
                        max_digits=14,
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount spent/committed",
                        max_digits=14,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Budget",
                "verbose_name_plural": "Program Budgets",
                "ordering": ["financial_year"],
                "unique_together": {("program", "financial_year")},
            },
        ),
    ]
